//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CENTRALCOMMENT
    {
        public int CENTRALCOMMENTSID { get; set; }
        public int CONTEXTID { get; set; }
        public string TYPE { get; set; }
        public string NOTES { get; set; }
        public int ISPUBLIC { get; set; }
        public string CREATEDBY { get; set; }
        public System.DateTime CREATEDDATE { get; set; }
    }
}
