//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CITYMASTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CITYMASTER()
        {
            this.EBUILDPRICEBOOKs = new HashSet<EBUILDPRICEBOOK>();
            this.EBUILDPRICEBOOKs1 = new HashSet<EBUILDPRICEBOOK>();
            this.EBUILDPRICEBOOKs2 = new HashSet<EBUILDPRICEBOOK>();
            this.EBUILDPRICEBOOKs3 = new HashSet<EBUILDPRICEBOOK>();
            this.EBUILDPRICINGs = new HashSet<EBUILDPRICING>();
            this.EBUILDPRICEBOOKs4 = new HashSet<EBUILDPRICEBOOK>();
            this.EBUILDPRICEBOOKs5 = new HashSet<EBUILDPRICEBOOK>();
            this.EBUILDPRICEBOOKs6 = new HashSet<EBUILDPRICEBOOK>();
            this.RATEMASTERs = new HashSet<RATEMASTER>();
            this.RATEMASTERs1 = new HashSet<RATEMASTER>();
            this.RATEMASTERs2 = new HashSet<RATEMASTER>();
            this.RATEMASTERs3 = new HashSet<RATEMASTER>();
            this.RATEMASTERPRICINGs = new HashSet<RATEMASTERPRICING>();
            this.RATEMASTERs4 = new HashSet<RATEMASTER>();
            this.RATEMASTERs5 = new HashSet<RATEMASTER>();
            this.RATEMASTERs6 = new HashSet<RATEMASTER>();
            this.RATEMASTERPRICINGs1 = new HashSet<RATEMASTERPRICING>();
        }
    
        public int CITYID { get; set; }
        public string NAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EBUILDPRICEBOOK> EBUILDPRICEBOOKs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EBUILDPRICEBOOK> EBUILDPRICEBOOKs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EBUILDPRICEBOOK> EBUILDPRICEBOOKs2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EBUILDPRICEBOOK> EBUILDPRICEBOOKs3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EBUILDPRICING> EBUILDPRICINGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EBUILDPRICEBOOK> EBUILDPRICEBOOKs4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EBUILDPRICEBOOK> EBUILDPRICEBOOKs5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EBUILDPRICEBOOK> EBUILDPRICEBOOKs6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RATEMASTER> RATEMASTERs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RATEMASTER> RATEMASTERs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RATEMASTER> RATEMASTERs2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RATEMASTER> RATEMASTERs3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RATEMASTERPRICING> RATEMASTERPRICINGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RATEMASTER> RATEMASTERs4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RATEMASTER> RATEMASTERs5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RATEMASTER> RATEMASTERs6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RATEMASTERPRICING> RATEMASTERPRICINGs1 { get; set; }
    }
}
