//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class R_TEContactOrganisationRepresentatives
    {
        public int UniqueId { get; set; }
        public int TEContactOrganisation { get; set; }
        public int TEContact { get; set; }
        public string Type { get; set; }
        public string Status { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
    
        public virtual TEContactOrganisation TEContactOrganisation1 { get; set; }
        public virtual TEContact TEContact1 { get; set; }
        public virtual TEContactOrganisation TEContactOrganisation2 { get; set; }
    }
}
