//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RATEMASTERPRICING
    {
        public int PRICINGID { get; set; }
        public int RATEMASTERID { get; set; }
        public Nullable<int> CATEGORYID { get; set; }
        public Nullable<int> SUBCATEGORYID { get; set; }
        public Nullable<int> WBSMASTERID { get; set; }
        public Nullable<int> CITYID { get; set; }
        public Nullable<int> PROJECTID { get; set; }
        public Nullable<int> PRODUCTID { get; set; }
        public decimal RATE { get; set; }
        public Nullable<decimal> OLDRATE { get; set; }
        public Nullable<int> WBSPARENTID { get; set; }
        public string REMARKS { get; set; }
    
        public virtual CATEGORYMASTER CATEGORYMASTER { get; set; }
        public virtual CATEGORYMASTER CATEGORYMASTER1 { get; set; }
        public virtual CITYMASTER CITYMASTER { get; set; }
        public virtual CITYMASTER CITYMASTER1 { get; set; }
        public virtual RATEMASTER RATEMASTER { get; set; }
        public virtual RATEMASTER RATEMASTER1 { get; set; }
        public virtual SUBCATEGORYMASTER SUBCATEGORYMASTER { get; set; }
        public virtual SUBCATEGORYMASTER SUBCATEGORYMASTER1 { get; set; }
        public virtual WBSMASTER WBSMASTER { get; set; }
        public virtual WBSMASTER WBSMASTER1 { get; set; }
    }
}
