//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleOfferSpecificationMigrationTable
    {
        public string uniqueid { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
        public string createdby { get; set; }
        public Nullable<System.DateTime> lastmodifiedon { get; set; }
        public string lastmodifiedby { get; set; }
        public Nullable<bool> isdeleted { get; set; }
        public string na19 { get; set; }
        public string descriptio7 { get; set; }
        public Nullable<bool> isacti17 { get; set; }
        public string sequencei2 { get; set; }
        public string remark6 { get; set; }
        public string specificationcategor2 { get; set; }
        public Nullable<int> categorysequenc1 { get; set; }
        public string specificationmasters { get; set; }
        public Nullable<int> sequencen2 { get; set; }
        public string offerh7 { get; set; }
        public string catego10 { get; set; }
        public string specificationsmaster { get; set; }
        public string specificationcolorcode { get; set; }
        public string saleorde9 { get; set; }
        public string priceelemen1 { get; set; }
    }
}
