//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TE_VendorInvoice_Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TE_VendorInvoice_Item()
        {
            this.TE_VendorInvoice_Item1 = new HashSet<TE_VendorInvoice_Item>();
        }
    
        public string CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string LastModifiedOn { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public int Uniqueid { get; set; }
        public string OldUniqueid { get; set; }
        public string Objectid { get; set; }
        public string Vendor_Account_Number_LIFNR { get; set; }
        public string Fugue_Reference_ID_FUGUE_ID { get; set; }
        public string CurrencyKey_WAERS { get; set; }
        public string TaxAmountDocumentCurrency_WMWST { get; set; }
        public string ItemText_SGTXT { get; set; }
        public string PurchasingDocumentNumber_EBELN { get; set; }
        public string ItemNumberPurchasingDocument_EBELP { get; set; }
        public string DocumentReferenceDocument_REF_DOC { get; set; }
        public string FiscalPeriod_REF_YEAR { get; set; }
        public string ItemReferenceDocument_REF_ITEM { get; set; }
        public string Quantity_MENGE { get; set; }
        public string MaterialNumber_MATNR { get; set; }
        public string GeneralLedgerAccount_HKONT { get; set; }
        public string AmountDocumentCurrency_WRBTR { get; set; }
        public string AmountGL_WRBTR_gl { get; set; }
        public string DebitCreditIndicator_SHKZG { get; set; }
        public string Taxsalespurchasescode_MWSKZ { get; set; }
        public string TaxsalespurchasescodeGL_MWSKZ_gl { get; set; }
        public string AssignmentNumber_DZUONR { get; set; }
        public string CostCenter_KOSTL { get; set; }
        public string OrderNumber_AUFNR { get; set; }
        public string CommitmentItem_FIPOS { get; set; }
        public string FundsCenter_FISTL { get; set; }
        public string WBSElement_WBS_ELEM { get; set; }
        public string BusinessArea_GSBER { get; set; }
        public string Quantity_MENGE_GL { get; set; }
        public string BaseUnitMeasure_MEINS_GL { get; set; }
        public string ItemText_SGTXT_GL { get; set; }
        public string EntrySheetNumber_SHEET_NO { get; set; }
        public string SheetLineNumber_SHEET_ITEM { get; set; }
        public string ConditionType_COND_TYPE { get; set; }
        public string DebitCredit_Indicator_SHKZG_HD { get; set; }
        public string Status { get; set; }
        public string ApprovedBy { get; set; }
        public string ApprovedOn { get; set; }
        public Nullable<int> VendorHeader_Uniqueid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TE_VendorInvoice_Item> TE_VendorInvoice_Item1 { get; set; }
        public virtual TE_VendorInvoice_Item TE_VendorInvoice_Item2 { get; set; }
    }
}
