//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TE_VendorInvoice_Header
    {
        public string CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string LastModifiedOn { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public int Uniqueid { get; set; }
        public string OldUniqueid { get; set; }
        public string Objectid { get; set; }
        public string Vendor_Account_Number_LIFNR { get; set; }
        public string Fugue_Reference_ID_FUGUE_ID { get; set; }
        public string Company_Code_BUKRS { get; set; }
        public string Invoice_Date_BLDAT { get; set; }
        public string Posting_Date_BUDAT { get; set; }
        public string Document_Type_BLART { get; set; }
        public string Amount_Document_Currency_WRBTR { get; set; }
        public string Currency_Key_WAERS { get; set; }
        public string Tax_salespurchases_code_MWSKZ { get; set; }
        public string Reference_Document_Number_XBLNR { get; set; }
        public string Calculate_tax_automatically_XMWST { get; set; }
        public string Business_Place_BUPLA { get; set; }
        public string Section_Code_SECCO { get; set; }
        public string Baseline_Date_for_Calculation_DZFBDT { get; set; }
        public string Unplanned_delivery_costs_BEZNK { get; set; }
        public string Item_Text_HDR_TEXT { get; set; }
        public string Indicator_withholding_tax_WITHT { get; set; }
        public string Withholding_taxcode_WT_WITHCD { get; set; }
        public string Withholding_TaxBaseAmount_BAPIQSSHB { get; set; }
        public string Withholding_TaxAmount_BAPIQBSHB1 { get; set; }
        public string Indicator_withholding_taxtype_WITHT1 { get; set; }
        public string Withholding_taxcode_WT_WITHCD1 { get; set; }
        public string Withholding_TaxBaseAmount_BAPIQSSHB1 { get; set; }
        public string Withholding_TaxAmount_BAPIQBSHB11 { get; set; }
        public string post_invoice_INV_IND { get; set; }
        public string Special_GL_Indicator_SPL { get; set; }
        public string Assignment_Number_ZUONR { get; set; }
        public string Document_Header_Text_BKTXT { get; set; }
        public string Status { get; set; }
        public string ApprovedBy { get; set; }
        public string ApprovedOn { get; set; }
        public string AccountingDocumentNumber_BELNR { get; set; }
        public string FiscalYear_FISC_YEAR { get; set; }
        public string ReturnCode_RETCODE { get; set; }
        public string ReturnMessage_MESSAGE { get; set; }
        public string ProjectName { get; set; }
        public string CustomerName { get; set; }
        public string UnitNumber { get; set; }
        public string Salevalue { get; set; }
        public string ProjectUniqueId { get; set; }
        public string CustomerUniqueId { get; set; }
        public string UnitUniqueId { get; set; }
        public string Notes { get; set; }
        public string BrokerageFee { get; set; }
    }
}
