//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEApplicant
    {
        public int ApplicantID { get; set; }
        public Nullable<int> ContextID { get; set; }
        public Nullable<int> ContactID { get; set; }
        public string Type { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public Nullable<int> LastModifiedBy_Id { get; set; }
        public string OldUniqueID { get; set; }
        public string Category { get; set; }
        public string GSTClassification { get; set; }
        public string Gstin { get; set; }
        public Nullable<bool> IsExistingCustomer { get; set; }
        public string IdentityRelationship { get; set; }
        public string RelationshipID { get; set; }
    }
}
