//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEApprovalProcessing
    {
        public int TRID { get; set; }
        public string TEAppObjectName { get; set; }
        public Nullable<int> TEAppObjectID { get; set; }
        public Nullable<int> LastApprovarID { get; set; }
        public Nullable<System.DateTime> LastApprovedDate { get; set; }
        public string LastApproverRemarks { get; set; }
        public Nullable<int> LastApproverLevel { get; set; }
        public string LastApprovarStage { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public string FinalRemarks { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
