//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEApprovalProcess
    {
        public int TRID { get; set; }
        public Nullable<int> TEApproveObjectID { get; set; }
        public Nullable<int> LastApprovarID { get; set; }
        public Nullable<System.DateTime> LastApprovedDate { get; set; }
        public string LastApproverRemarks { get; set; }
        public Nullable<int> LastApprovalLevel { get; set; }
        public Nullable<int> LastApprovalStage { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public string OldUniqueID { get; set; }
    
        public virtual TEApproveGroupUser TEApproveGroupUser { get; set; }
        public virtual TEApproveLevel TEApproveLevel { get; set; }
        public virtual TEApproveObject TEApproveObject { get; set; }
        public virtual TEApproveStage TEApproveStage { get; set; }
    }
}
