//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEAsset
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TEAsset()
        {
            this.TEAssetAllocations = new HashSet<TEAssetAllocation>();
            this.TEAssetAllocations1 = new HashSet<TEAssetAllocation>();
            this.TEAssetAllocations2 = new HashSet<TEAssetAllocation>();
            this.TEAssetLosses = new HashSet<TEAssetLoss>();
            this.TEAssetLosses1 = new HashSet<TEAssetLoss>();
            this.TEAssetLosses2 = new HashSet<TEAssetLoss>();
            this.TEAssetScrappings = new HashSet<TEAssetScrapping>();
            this.TEAssetScrappings1 = new HashSet<TEAssetScrapping>();
            this.TEAssetScrappings2 = new HashSet<TEAssetScrapping>();
            this.TEAssetVariantMappings = new HashSet<TEAssetVariantMapping>();
            this.TEAssetVariantMappings1 = new HashSet<TEAssetVariantMapping>();
            this.TEAssetVariantMappings2 = new HashSet<TEAssetVariantMapping>();
        }
    
        public int Uniqueid { get; set; }
        public string AssetType { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> SubmittedOn { get; set; }
        public string SubmittedBy { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
        public string ApprovedBy { get; set; }
        public bool IsDeleted { get; set; }
        public string Status { get; set; }
        public Nullable<int> TEAssetSubCategoryID { get; set; }
        public Nullable<int> TECompanyID { get; set; }
        public string ManufacturerSerialNo { get; set; }
        public string TESerialNo { get; set; }
        public string PONumber { get; set; }
        public Nullable<System.DateTime> PODate { get; set; }
        public Nullable<System.DateTime> InstallationDate { get; set; }
        public Nullable<System.DateTime> WarrantyExpiryDate { get; set; }
        public string Brand { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public Nullable<bool> IsChildAsset { get; set; }
        public Nullable<int> ParentAssetCode { get; set; }
        public Nullable<decimal> AssetQuantity { get; set; }
        public Nullable<decimal> AllocatedQuantity { get; set; }
        public Nullable<decimal> UsefullLife { get; set; }
        public Nullable<decimal> BookValue { get; set; }
        public Nullable<decimal> SalvageValue { get; set; }
        public string MobileNumber { get; set; }
        public string ServiceProvider { get; set; }
        public Nullable<bool> IsPostPaid { get; set; }
        public string PlanName { get; set; }
        public Nullable<bool> LeasedAsset { get; set; }
        public Nullable<decimal> MonthlyLeaseCharges { get; set; }
        public string Remarks { get; set; }
        public string MobileType { get; set; }
        public Nullable<int> BillingAcntNo { get; set; }
        public bool IsMobileAsset { get; set; }
        public string ModelNo { get; set; }
    
        public virtual TEAssetSubCategory TEAssetSubCategory { get; set; }
        public virtual TEAssetSubCategory TEAssetSubCategory1 { get; set; }
        public virtual TEAssetSubCategory TEAssetSubCategory2 { get; set; }
        public virtual TECompany TECompany { get; set; }
        public virtual TECompany TECompany1 { get; set; }
        public virtual TECompany TECompany2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEAssetAllocation> TEAssetAllocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEAssetAllocation> TEAssetAllocations1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEAssetAllocation> TEAssetAllocations2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEAssetLoss> TEAssetLosses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEAssetLoss> TEAssetLosses1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEAssetLoss> TEAssetLosses2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEAssetScrapping> TEAssetScrappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEAssetScrapping> TEAssetScrappings1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEAssetScrapping> TEAssetScrappings2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEAssetVariantMapping> TEAssetVariantMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEAssetVariantMapping> TEAssetVariantMappings1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEAssetVariantMapping> TEAssetVariantMappings2 { get; set; }
    }
}
