//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEAssestRequestation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TEAssestRequestation()
        {
            this.TEAssestRequestationItems = new HashSet<TEAssestRequestationItem>();
            this.TEAssestRequestationItems1 = new HashSet<TEAssestRequestationItem>();
            this.TEAssestRequestationItems2 = new HashSet<TEAssestRequestationItem>();
            this.TEAssetAllocations = new HashSet<TEAssetAllocation>();
            this.TEAssetAllocations1 = new HashSet<TEAssetAllocation>();
            this.TEAssetAllocations2 = new HashSet<TEAssetAllocation>();
        }
    
        public int Uniqueid { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> SubmittedOn { get; set; }
        public string SubmittedBy { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
        public string ApprovedBy { get; set; }
        public bool IsDeleted { get; set; }
        public string Status { get; set; }
        public string EmployeeID { get; set; }
        public Nullable<int> TEDepartments { get; set; }
        public Nullable<int> TEWorkDesignation { get; set; }
        public Nullable<int> TEWorkLocations { get; set; }
        public Nullable<System.DateTime> ExpectedDOJ { get; set; }
        public string AllocatedBy { get; set; }
        public string SpecialRequirements { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEAssestRequestationItem> TEAssestRequestationItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEAssestRequestationItem> TEAssestRequestationItems1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEAssestRequestationItem> TEAssestRequestationItems2 { get; set; }
        public virtual TEDepartment TEDepartment { get; set; }
        public virtual TEDepartment TEDepartment1 { get; set; }
        public virtual TEDepartment TEDepartment2 { get; set; }
        public virtual TEWorkingDesignation TEWorkingDesignation { get; set; }
        public virtual TEWorkLocation TEWorkLocation { get; set; }
        public virtual TEWorkingDesignation TEWorkingDesignation1 { get; set; }
        public virtual TEWorkLocation TEWorkLocation1 { get; set; }
        public virtual TEWorkingDesignation TEWorkingDesignation2 { get; set; }
        public virtual TEWorkLocation TEWorkLocation2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEAssetAllocation> TEAssetAllocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEAssetAllocation> TEAssetAllocations1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEAssetAllocation> TEAssetAllocations2 { get; set; }
    }
}
