//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEAssetVariantType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TEAssetVariantType()
        {
            this.TEAssetVariantValues = new HashSet<TEAssetVariantValue>();
            this.TEAssetVariantValues1 = new HashSet<TEAssetVariantValue>();
            this.TEAssetVariantValues2 = new HashSet<TEAssetVariantValue>();
        }
    
        public int Uniqueid { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> SubmittedOn { get; set; }
        public string SubmittedBy { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
        public string ApprovedBy { get; set; }
        public bool IsDeleted { get; set; }
        public string Status { get; set; }
        public Nullable<int> TEAssetSubCategoryID { get; set; }
    
        public virtual TEAssetSubCategory TEAssetSubCategory { get; set; }
        public virtual TEAssetSubCategory TEAssetSubCategory1 { get; set; }
        public virtual TEAssetSubCategory TEAssetSubCategory2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEAssetVariantValue> TEAssetVariantValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEAssetVariantValue> TEAssetVariantValues1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEAssetVariantValue> TEAssetVariantValues2 { get; set; }
    }
}
