//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEAssetAllocation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TEAssetAllocation()
        {
            this.TEAssetReturns = new HashSet<TEAssetReturn>();
            this.TEAssetReturns1 = new HashSet<TEAssetReturn>();
            this.TEAssetReturns2 = new HashSet<TEAssetReturn>();
            this.TEEmpClearanceDetails = new HashSet<TEEmpClearanceDetail>();
            this.TEEmpClearanceDetails1 = new HashSet<TEEmpClearanceDetail>();
            this.TEEmpClearanceDetails2 = new HashSet<TEEmpClearanceDetail>();
        }
    
        public int Uniqueid { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> SubmittedOn { get; set; }
        public string SubmittedBy { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
        public string ApprovedBy { get; set; }
        public bool IsDeleted { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> AllocationDate { get; set; }
        public Nullable<int> AllocatedBy { get; set; }
        public Nullable<int> AllocateTo { get; set; }
        public Nullable<int> ResponsibleEmployee { get; set; }
        public Nullable<int> TEWorkLocation { get; set; }
        public Nullable<int> TEAssetID { get; set; }
        public Nullable<int> TEAssetRequisitionID { get; set; }
    
        public virtual TEAssestRequestation TEAssestRequestation { get; set; }
        public virtual TEAssestRequestation TEAssestRequestation1 { get; set; }
        public virtual TEAssestRequestation TEAssestRequestation2 { get; set; }
        public virtual TEAsset TEAsset { get; set; }
        public virtual TEAsset TEAsset1 { get; set; }
        public virtual TEAsset TEAsset2 { get; set; }
        public virtual TEEmpBasicInfo TEEmpBasicInfo { get; set; }
        public virtual TEEmpBasicInfo TEEmpBasicInfo1 { get; set; }
        public virtual TEEmpBasicInfo TEEmpBasicInfo2 { get; set; }
        public virtual TEEmpBasicInfo TEEmpBasicInfo3 { get; set; }
        public virtual TEEmpBasicInfo TEEmpBasicInfo4 { get; set; }
        public virtual TEEmpBasicInfo TEEmpBasicInfo5 { get; set; }
        public virtual TEEmpBasicInfo TEEmpBasicInfo6 { get; set; }
        public virtual TEEmpBasicInfo TEEmpBasicInfo7 { get; set; }
        public virtual TEEmpBasicInfo TEEmpBasicInfo8 { get; set; }
        public virtual TEWorkLocation TEWorkLocation1 { get; set; }
        public virtual TEWorkLocation TEWorkLocation2 { get; set; }
        public virtual TEWorkLocation TEWorkLocation3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEAssetReturn> TEAssetReturns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEAssetReturn> TEAssetReturns1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEAssetReturn> TEAssetReturns2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEmpClearanceDetail> TEEmpClearanceDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEmpClearanceDetail> TEEmpClearanceDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEmpClearanceDetail> TEEmpClearanceDetails2 { get; set; }
    }
}
