//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEBusinessPartnerBrokerFee
    {
        public int BusinessPartnerBrokerFeeID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<decimal> Fee { get; set; }
        public string FeeType { get; set; }
        public string City { get; set; }
        public Nullable<int> BusinessPartnerID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> LastModifiedBy_Id { get; set; }
        public string OldUniqueID { get; set; }
    
        public virtual TEBusinessPartner TEBusinessPartner { get; set; }
    }
}
