//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEClaimBookLogs_Visibility
    {
        public int UniqueId { get; set; }
        public Nullable<int> ClaimBookLog { get; set; }
        public Nullable<int> Employee { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual TEClaimBookLog TEClaimBookLog { get; set; }
        public virtual TEClaimBookLog TEClaimBookLog1 { get; set; }
        public virtual TEEmpBasicInfo TEEmpBasicInfo { get; set; }
        public virtual TEEmpBasicInfo TEEmpBasicInfo1 { get; set; }
    }
}
