//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEDynamicGroupQuery
    {
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string ObjectId { get; set; }
        public int UniqueId { get; set; }
        public Nullable<int> TERelationshipCategory { get; set; }
        public Nullable<int> RelationshipId { get; set; }
        public string Name { get; set; }
        public bool IsAnd { get; set; }
        public string Description { get; set; }
    
        public virtual TERelationshipCategory TERelationshipCategory1 { get; set; }
    }
}
