//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEEmpClearanceDetail
    {
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime LastModifiedOn { get; set; }
        public string ObjectId { get; set; }
        public string OldUniqueId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public int UniqueId { get; set; }
        public Nullable<int> TEEmpBasicInfo { get; set; }
        public Nullable<int> TEClearanceMaster { get; set; }
        public string Item { get; set; }
        public string SerialNumber { get; set; }
        public System.DateTime IssueDate { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> ClearanceAmount { get; set; }
        public string ClearedBy { get; set; }
        public Nullable<System.DateTime> ClearedOn { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
        public Nullable<bool> IsCleared { get; set; }
        public string Remarks { get; set; }
        public string TEEmpSeparation { get; set; }
        public Nullable<int> TEAssetAllocationID { get; set; }
    
        public virtual TEAssetAllocation TEAssetAllocation { get; set; }
        public virtual TEAssetAllocation TEAssetAllocation1 { get; set; }
        public virtual TEAssetAllocation TEAssetAllocation2 { get; set; }
        public virtual TEClearanceMaster TEClearanceMaster1 { get; set; }
        public virtual TEEmpBasicInfo TEEmpBasicInfo1 { get; set; }
    }
}
