//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEEmpAttendence
    {
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public string LastModifiedBy { get; set; }
        public bool IsDeleted { get; set; }
        public int Uniqueid { get; set; }
        public string OldUniqueid { get; set; }
        public string Objectid { get; set; }
        public Nullable<int> TEEmpBasicInfo { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.TimeSpan> InTime { get; set; }
        public Nullable<System.TimeSpan> OutTime { get; set; }
        public string SubmittedByTEEmpBasicInfo { get; set; }
        public Nullable<System.DateTime> SubmittedOn { get; set; }
        public Nullable<decimal> NetDuration { get; set; }
        public string TypeOfAttendence { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
        public string Status { get; set; }
        public string ResionForRegularize { get; set; }
        public string ReasonForRejection { get; set; }
        public string LeaveName { get; set; }
        public string LeaveType { get; set; }
        public string ColorCode { get; set; }
        public string ProcessedBy { get; set; }
        public Nullable<System.DateTime> ProcessedOn { get; set; }
        public string comment { get; set; }
        public string SourceDevice { get; set; }
        public Nullable<int> LeaveReferenceId { get; set; }
        public Nullable<bool> IsCoreHoursCompleted { get; set; }
        public Nullable<decimal> AttendanceCount { get; set; }
        public Nullable<decimal> LeaveCount { get; set; }
        public bool IsExceptionalAttendance { get; set; }
        public bool IsExceptionalFullDayAttendance { get; set; }
        public Nullable<decimal> LOPCount { get; set; }
    
        public virtual TEEmpBasicInfo TEEmpBasicInfo1 { get; set; }
        public virtual TEEmpBasicInfo TEEmpBasicInfo2 { get; set; }
        public virtual TEEmpBasicInfo TEEmpBasicInfo3 { get; set; }
        public virtual TEEmpBasicInfo TEEmpBasicInfo4 { get; set; }
        public virtual TEEmpBasicInfo TEEmpBasicInfo5 { get; set; }
        public virtual TEEmpBasicInfo TEEmpBasicInfo6 { get; set; }
        public virtual TEEmpBasicInfo TEEmpBasicInfo7 { get; set; }
        public virtual TEEmpBasicInfo TEEmpBasicInfo8 { get; set; }
        public virtual TEEmpLeaveApplication TEEmpLeaveApplication { get; set; }
    }
}
