//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEEmpBasicInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TEEmpBasicInfo()
        {
            this.TEAssetAllocations = new HashSet<TEAssetAllocation>();
            this.TEAssetAllocations1 = new HashSet<TEAssetAllocation>();
            this.TEAssetAllocations2 = new HashSet<TEAssetAllocation>();
            this.TEAssetAllocations3 = new HashSet<TEAssetAllocation>();
            this.TEAssetAllocations4 = new HashSet<TEAssetAllocation>();
            this.TEAssetAllocations5 = new HashSet<TEAssetAllocation>();
            this.TEAssetAllocations6 = new HashSet<TEAssetAllocation>();
            this.TEAssetAllocations7 = new HashSet<TEAssetAllocation>();
            this.TEAssetAllocations8 = new HashSet<TEAssetAllocation>();
            this.TEAssetLosses = new HashSet<TEAssetLoss>();
            this.TEAssetLosses1 = new HashSet<TEAssetLoss>();
            this.TEAssetLosses2 = new HashSet<TEAssetLoss>();
            this.TEAssetLosses3 = new HashSet<TEAssetLoss>();
            this.TEAssetLosses4 = new HashSet<TEAssetLoss>();
            this.TEAssetLosses5 = new HashSet<TEAssetLoss>();
            this.TEAssetReturns = new HashSet<TEAssetReturn>();
            this.TEAssetReturns1 = new HashSet<TEAssetReturn>();
            this.TEAssetReturns2 = new HashSet<TEAssetReturn>();
            this.TEClaimApprovers = new HashSet<TEClaimApprover>();
            this.TEClaimApprovers1 = new HashSet<TEClaimApprover>();
            this.TEClaimBooks = new HashSet<TEClaimBook>();
            this.TEClaimBooks1 = new HashSet<TEClaimBook>();
            this.TEClaimBooks2 = new HashSet<TEClaimBook>();
            this.TEClaimBookLogs = new HashSet<TEClaimBookLog>();
            this.TEClaimBookLogs1 = new HashSet<TEClaimBookLog>();
            this.TEClaimBookLogs_Visibility = new HashSet<TEClaimBookLogs_Visibility>();
            this.TEClaimBookLogs_Visibility1 = new HashSet<TEClaimBookLogs_Visibility>();
            this.TEClaimFundCenters = new HashSet<TEClaimFundCenter>();
            this.TEClaimFundCenters1 = new HashSet<TEClaimFundCenter>();
            this.TEClaimFundCenters2 = new HashSet<TEClaimFundCenter>();
            this.TEClaimItems = new HashSet<TEClaimItem>();
            this.TEClaimItems1 = new HashSet<TEClaimItem>();
            this.TEEMPAddresses = new HashSet<TEEMPAddress>();
            this.TEEMPAddresses1 = new HashSet<TEEMPAddress>();
            this.TEEMPAddresses2 = new HashSet<TEEMPAddress>();
            this.TEEmpAssignmentDetails = new HashSet<TEEmpAssignmentDetail>();
            this.TEEmpAssignmentDetails1 = new HashSet<TEEmpAssignmentDetail>();
            this.TEEmpAssignmentDetails2 = new HashSet<TEEmpAssignmentDetail>();
            this.TEEmpAssignmentDetails3 = new HashSet<TEEmpAssignmentDetail>();
            this.TEEmpAssignmentDetails4 = new HashSet<TEEmpAssignmentDetail>();
            this.TEEmpAssignmentDetails5 = new HashSet<TEEmpAssignmentDetail>();
            this.TEEmpAssignmentDetails6 = new HashSet<TEEmpAssignmentDetail>();
            this.TEEmpAttendences = new HashSet<TEEmpAttendence>();
            this.TEEmpAttendences1 = new HashSet<TEEmpAttendence>();
            this.TEEmpAttendences2 = new HashSet<TEEmpAttendence>();
            this.TEEmpAttendences3 = new HashSet<TEEmpAttendence>();
            this.TEEmpAttendences4 = new HashSet<TEEmpAttendence>();
            this.TEEmpAttendences5 = new HashSet<TEEmpAttendence>();
            this.TEEmpAttendences6 = new HashSet<TEEmpAttendence>();
            this.TEEmpAttendences7 = new HashSet<TEEmpAttendence>();
            this.TEEmpBankDetails = new HashSet<TEEmpBankDetail>();
            this.TEEmpBankDetails1 = new HashSet<TEEmpBankDetail>();
            this.TEEmpBankDetails2 = new HashSet<TEEmpBankDetail>();
            this.TEEmpBasicInfoPendingDetails = new HashSet<TEEmpBasicInfoPendingDetail>();
            this.TEEmpBenefits = new HashSet<TEEmpBenefit>();
            this.TEEmpBenefits1 = new HashSet<TEEmpBenefit>();
            this.TEEmpBenefits2 = new HashSet<TEEmpBenefit>();
            this.TEEmpEducationDetails = new HashSet<TEEmpEducationDetail>();
            this.TEEmpEducationDetails1 = new HashSet<TEEmpEducationDetail>();
            this.TEEmpEducationDetails2 = new HashSet<TEEmpEducationDetail>();
            this.TEEmpEmergencyContacts = new HashSet<TEEmpEmergencyContact>();
            this.TEEmpEmergencyContacts1 = new HashSet<TEEmpEmergencyContact>();
            this.TEEmpEmergencyContacts2 = new HashSet<TEEmpEmergencyContact>();
            this.TEEmpExperienceDetails = new HashSet<TEEmpExperienceDetail>();
            this.TEEmpExperienceDetails1 = new HashSet<TEEmpExperienceDetail>();
            this.TEEmpExperienceDetails2 = new HashSet<TEEmpExperienceDetail>();
            this.TEEmpFamilyDetails = new HashSet<TEEmpFamilyDetail>();
            this.TEEmpFamilyDetails1 = new HashSet<TEEmpFamilyDetail>();
            this.TEEmpFamilyDetails2 = new HashSet<TEEmpFamilyDetail>();
            this.TEEmpInsuranceDetails = new HashSet<TEEmpInsuranceDetail>();
            this.TEEmpInsuranceDetails1 = new HashSet<TEEmpInsuranceDetail>();
            this.TEEmpInsuranceDetails2 = new HashSet<TEEmpInsuranceDetail>();
            this.TEEmpLanguages = new HashSet<TEEmpLanguage>();
            this.TEEmpLanguages1 = new HashSet<TEEmpLanguage>();
            this.TEEmpLanguages2 = new HashSet<TEEmpLanguage>();
            this.TEEmpLeaveApplications = new HashSet<TEEmpLeaveApplication>();
            this.TEEmpLeavesSummaries = new HashSet<TEEmpLeavesSummary>();
            this.TEEmpLeaveApplications1 = new HashSet<TEEmpLeaveApplication>();
            this.TEEmpLeaveApplications2 = new HashSet<TEEmpLeaveApplication>();
            this.TEEmpLeavesSummaries1 = new HashSet<TEEmpLeavesSummary>();
            this.TEEmpLeavesSummaries2 = new HashSet<TEEmpLeavesSummary>();
            this.TEEmpMobileEligibilities = new HashSet<TEEmpMobileEligibility>();
            this.TEEmpMobileEligibilities1 = new HashSet<TEEmpMobileEligibility>();
            this.TEEmpMobileEligibilities2 = new HashSet<TEEmpMobileEligibility>();
            this.TEEmpOtherDetails = new HashSet<TEEmpOtherDetail>();
            this.TEEmpOtherDetails1 = new HashSet<TEEmpOtherDetail>();
            this.TEEmpOtherDetails2 = new HashSet<TEEmpOtherDetail>();
            this.TEEmpReferences = new HashSet<TEEmpReference>();
            this.TEEmpReferences1 = new HashSet<TEEmpReference>();
            this.TEEmpReferences2 = new HashSet<TEEmpReference>();
            this.TEEmpSpecialLeaveApplications = new HashSet<TEEmpSpecialLeaveApplication>();
            this.TEEmpSpecialLeaveApplications1 = new HashSet<TEEmpSpecialLeaveApplication>();
            this.TEEmpSpecialLeaveApplications2 = new HashSet<TEEmpSpecialLeaveApplication>();
            this.TEEmpSpecialLeaveApplications3 = new HashSet<TEEmpSpecialLeaveApplication>();
            this.TEEmpSpecialLeaveApplications4 = new HashSet<TEEmpSpecialLeaveApplication>();
            this.TEEmpSpecialLeaveApplications5 = new HashSet<TEEmpSpecialLeaveApplication>();
            this.TEEmpSpecialLeaveApplications6 = new HashSet<TEEmpSpecialLeaveApplication>();
            this.TEEmpSpecialLeaveApplications7 = new HashSet<TEEmpSpecialLeaveApplication>();
            this.TEEmpSpecialLeaveApplications8 = new HashSet<TEEmpSpecialLeaveApplication>();
            this.TEEmpWorkSchedules = new HashSet<TEEmpWorkSchedule>();
            this.TEEmpWorkSchedules1 = new HashSet<TEEmpWorkSchedule>();
            this.TEEmpWorkSchedules2 = new HashSet<TEEmpWorkSchedule>();
            this.TEIssuesDispositions = new HashSet<TEIssuesDisposition>();
            this.TEIssuesDispositions1 = new HashSet<TEIssuesDisposition>();
            this.TEIssuesDispositions2 = new HashSet<TEIssuesDisposition>();
            this.TEMobileBillDetails = new HashSet<TEMobileBillDetail>();
            this.TEMobileBillDetails1 = new HashSet<TEMobileBillDetail>();
            this.TEMobileBillDetails2 = new HashSet<TEMobileBillDetail>();
            this.TEMobileBillDetails3 = new HashSet<TEMobileBillDetail>();
            this.TEMobileBillDetails4 = new HashSet<TEMobileBillDetail>();
            this.TEPayRollLeaveEncashmentReports = new HashSet<TEPayRollLeaveEncashmentReport>();
            this.TEPayRollTransferReports = new HashSet<TEPayRollTransferReport>();
            this.TEPayRollFFReports = new HashSet<TEPayRollFFReport>();
            this.TEPayRollAbscondingReports = new HashSet<TEPayRollAbscondingReport>();
            this.TEPayRollNewJoineeReports = new HashSet<TEPayRollNewJoineeReport>();
            this.TEPayRollResignationReports = new HashSet<TEPayRollResignationReport>();
            this.TEPayRollBankAcReports = new HashSet<TEPayRollBankAcReport>();
            this.TEPayRollLOPReports = new HashSet<TEPayRollLOPReport>();
            this.TEPayRollLeaveReports = new HashSet<TEPayRollLeaveReport>();
            this.TESurveyStatus = new HashSet<TESurveyStatu>();
            this.TESurveyStatus1 = new HashSet<TESurveyStatu>();
            this.TESurveyStatus2 = new HashSet<TESurveyStatu>();
            this.TEEmpClearanceDetails = new HashSet<TEEmpClearanceDetail>();
            this.TEEmpSeparations = new HashSet<TEEmpSeparation>();
        }
    
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public string LastModifiedBy { get; set; }
        public bool IsDeleted { get; set; }
        public int Uniqueid { get; set; }
        public string OldUniqueid { get; set; }
        public string Objectid { get; set; }
        public string EmployeeId { get; set; }
        public string UserId { get; set; }
        public string TEUser { get; set; }
        public string Salutation { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string RelationOf { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Gender { get; set; }
        public string MaritalStatus { get; set; }
        public Nullable<System.DateTime> DateOfMarriage { get; set; }
        public string LandlineNo { get; set; }
        public string Mobile { get; set; }
        public string PersonalEmail { get; set; }
        public string OfficialEmail { get; set; }
        public string BloodGroup { get; set; }
        public string Photo { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public Nullable<System.DateTime> DateOfConfirmation { get; set; }
        public Nullable<decimal> TEExperience { get; set; }
        public Nullable<decimal> PrevExperience { get; set; }
        public Nullable<decimal> TotalExperience { get; set; }
        public Nullable<System.DateTime> ProposedDOJ { get; set; }
        public Nullable<System.DateTime> ProposedDOL { get; set; }
        public Nullable<System.DateTime> DOL { get; set; }
        public string Reason { get; set; }
        public string Citizenship { get; set; }
        public string ResidentStatus { get; set; }
        public string TETag { get; set; }
        public Nullable<System.DateTime> InitiatedDOL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEAssetAllocation> TEAssetAllocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEAssetAllocation> TEAssetAllocations1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEAssetAllocation> TEAssetAllocations2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEAssetAllocation> TEAssetAllocations3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEAssetAllocation> TEAssetAllocations4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEAssetAllocation> TEAssetAllocations5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEAssetAllocation> TEAssetAllocations6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEAssetAllocation> TEAssetAllocations7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEAssetAllocation> TEAssetAllocations8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEAssetLoss> TEAssetLosses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEAssetLoss> TEAssetLosses1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEAssetLoss> TEAssetLosses2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEAssetLoss> TEAssetLosses3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEAssetLoss> TEAssetLosses4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEAssetLoss> TEAssetLosses5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEAssetReturn> TEAssetReturns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEAssetReturn> TEAssetReturns1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEAssetReturn> TEAssetReturns2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEClaimApprover> TEClaimApprovers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEClaimApprover> TEClaimApprovers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEClaimBook> TEClaimBooks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEClaimBook> TEClaimBooks1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEClaimBook> TEClaimBooks2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEClaimBookLog> TEClaimBookLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEClaimBookLog> TEClaimBookLogs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEClaimBookLogs_Visibility> TEClaimBookLogs_Visibility { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEClaimBookLogs_Visibility> TEClaimBookLogs_Visibility1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEClaimFundCenter> TEClaimFundCenters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEClaimFundCenter> TEClaimFundCenters1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEClaimFundCenter> TEClaimFundCenters2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEClaimItem> TEClaimItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEClaimItem> TEClaimItems1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEMPAddress> TEEMPAddresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEMPAddress> TEEMPAddresses1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEMPAddress> TEEMPAddresses2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEmpAssignmentDetail> TEEmpAssignmentDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEmpAssignmentDetail> TEEmpAssignmentDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEmpAssignmentDetail> TEEmpAssignmentDetails2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEmpAssignmentDetail> TEEmpAssignmentDetails3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEmpAssignmentDetail> TEEmpAssignmentDetails4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEmpAssignmentDetail> TEEmpAssignmentDetails5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEmpAssignmentDetail> TEEmpAssignmentDetails6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEmpAttendence> TEEmpAttendences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEmpAttendence> TEEmpAttendences1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEmpAttendence> TEEmpAttendences2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEmpAttendence> TEEmpAttendences3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEmpAttendence> TEEmpAttendences4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEmpAttendence> TEEmpAttendences5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEmpAttendence> TEEmpAttendences6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEmpAttendence> TEEmpAttendences7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEmpBankDetail> TEEmpBankDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEmpBankDetail> TEEmpBankDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEmpBankDetail> TEEmpBankDetails2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEmpBasicInfoPendingDetail> TEEmpBasicInfoPendingDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEmpBenefit> TEEmpBenefits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEmpBenefit> TEEmpBenefits1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEmpBenefit> TEEmpBenefits2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEmpEducationDetail> TEEmpEducationDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEmpEducationDetail> TEEmpEducationDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEmpEducationDetail> TEEmpEducationDetails2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEmpEmergencyContact> TEEmpEmergencyContacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEmpEmergencyContact> TEEmpEmergencyContacts1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEmpEmergencyContact> TEEmpEmergencyContacts2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEmpExperienceDetail> TEEmpExperienceDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEmpExperienceDetail> TEEmpExperienceDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEmpExperienceDetail> TEEmpExperienceDetails2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEmpFamilyDetail> TEEmpFamilyDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEmpFamilyDetail> TEEmpFamilyDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEmpFamilyDetail> TEEmpFamilyDetails2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEmpInsuranceDetail> TEEmpInsuranceDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEmpInsuranceDetail> TEEmpInsuranceDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEmpInsuranceDetail> TEEmpInsuranceDetails2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEmpLanguage> TEEmpLanguages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEmpLanguage> TEEmpLanguages1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEmpLanguage> TEEmpLanguages2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEmpLeaveApplication> TEEmpLeaveApplications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEmpLeavesSummary> TEEmpLeavesSummaries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEmpLeaveApplication> TEEmpLeaveApplications1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEmpLeaveApplication> TEEmpLeaveApplications2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEmpLeavesSummary> TEEmpLeavesSummaries1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEmpLeavesSummary> TEEmpLeavesSummaries2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEmpMobileEligibility> TEEmpMobileEligibilities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEmpMobileEligibility> TEEmpMobileEligibilities1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEmpMobileEligibility> TEEmpMobileEligibilities2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEmpOtherDetail> TEEmpOtherDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEmpOtherDetail> TEEmpOtherDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEmpOtherDetail> TEEmpOtherDetails2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEmpReference> TEEmpReferences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEmpReference> TEEmpReferences1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEmpReference> TEEmpReferences2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEmpSpecialLeaveApplication> TEEmpSpecialLeaveApplications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEmpSpecialLeaveApplication> TEEmpSpecialLeaveApplications1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEmpSpecialLeaveApplication> TEEmpSpecialLeaveApplications2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEmpSpecialLeaveApplication> TEEmpSpecialLeaveApplications3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEmpSpecialLeaveApplication> TEEmpSpecialLeaveApplications4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEmpSpecialLeaveApplication> TEEmpSpecialLeaveApplications5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEmpSpecialLeaveApplication> TEEmpSpecialLeaveApplications6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEmpSpecialLeaveApplication> TEEmpSpecialLeaveApplications7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEmpSpecialLeaveApplication> TEEmpSpecialLeaveApplications8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEmpWorkSchedule> TEEmpWorkSchedules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEmpWorkSchedule> TEEmpWorkSchedules1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEmpWorkSchedule> TEEmpWorkSchedules2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEIssuesDisposition> TEIssuesDispositions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEIssuesDisposition> TEIssuesDispositions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEIssuesDisposition> TEIssuesDispositions2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEMobileBillDetail> TEMobileBillDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEMobileBillDetail> TEMobileBillDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEMobileBillDetail> TEMobileBillDetails2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEMobileBillDetail> TEMobileBillDetails3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEMobileBillDetail> TEMobileBillDetails4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEPayRollLeaveEncashmentReport> TEPayRollLeaveEncashmentReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEPayRollTransferReport> TEPayRollTransferReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEPayRollFFReport> TEPayRollFFReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEPayRollAbscondingReport> TEPayRollAbscondingReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEPayRollNewJoineeReport> TEPayRollNewJoineeReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEPayRollResignationReport> TEPayRollResignationReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEPayRollBankAcReport> TEPayRollBankAcReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEPayRollLOPReport> TEPayRollLOPReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEPayRollLeaveReport> TEPayRollLeaveReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TESurveyStatu> TESurveyStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TESurveyStatu> TESurveyStatus1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TESurveyStatu> TESurveyStatus2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEmpClearanceDetail> TEEmpClearanceDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEmpSeparation> TEEmpSeparations { get; set; }
    }
}
