//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEEmpSeparationQuestionBucket
    {
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime LastmodifiedOn { get; set; }
        public string ObjectId { get; set; }
        public string OldUniqueId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public int UniqueId { get; set; }
        public string TEQuestionMaster { get; set; }
        public Nullable<int> Band { get; set; }
        public Nullable<int> Grade { get; set; }
        public string Designation { get; set; }
        public string EmploymentType { get; set; }
        public string Status { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
        public string BucketName { get; set; }
    }
}
