//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEInterestInvoiceBreakup
    {
        public int UniqueId { get; set; }
        public Nullable<int> InvoiceRefID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> InterestFrom { get; set; }
        public Nullable<System.DateTime> InterestTo { get; set; }
        public Nullable<int> InterestDays { get; set; }
        public Nullable<decimal> InterestRate { get; set; }
        public Nullable<decimal> InterestAmount { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> GenDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
