//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEIssue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TEIssue()
        {
            this.TEIssuesDispositions = new HashSet<TEIssuesDisposition>();
            this.TEIssuesDispositions1 = new HashSet<TEIssuesDisposition>();
            this.TEIssuesDispositions2 = new HashSet<TEIssuesDisposition>();
        }
    
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public string LastModifiedBy { get; set; }
        public bool IsDeleted { get; set; }
        public int Uniqueid { get; set; }
        public string OldUniqueid { get; set; }
        public string Objectid { get; set; }
        public Nullable<int> ISSUEID { get; set; }
        public string UNITONBOARDINGID { get; set; }
        public string Subject { get; set; }
        public string Descritpion { get; set; }
        public string Summary { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> ParentCatID { get; set; }
        public Nullable<int> QueueID { get; set; }
        public Nullable<System.DateTime> Closed_Date { get; set; }
        public string Priority { get; set; }
        public string Status { get; set; }
        public string Stage { get; set; }
        public Nullable<int> AssignedTo { get; set; }
        public string ClosedBy { get; set; }
        public Nullable<int> RaisedBy { get; set; }
        public string Attachments { get; set; }
        public Nullable<System.DateTime> Estimated_Close_date { get; set; }
        public Nullable<System.DateTime> Actual_close_date { get; set; }
        public string Assigned { get; set; }
        public string Start { get; set; }
        public string Pasue { get; set; }
        public string Resolved_Date { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public string UnitID { get; set; }
        public string AREATYPE { get; set; }
        public Nullable<System.DateTime> Scheduled_Date { get; set; }
        public string RateUS { get; set; }
        public Nullable<int> COSTINVOLED { get; set; }
        public Nullable<int> EstimateCOST { get; set; }
        public Nullable<int> ActualCost { get; set; }
        public Nullable<int> LaborCost { get; set; }
        public Nullable<int> MaterialCost { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
        public string AvailableStart { get; set; }
        public string AvailableEnd { get; set; }
        public string Feedback { get; set; }
        public string FeedbackTechnician { get; set; }
        public string PrefferedTime { get; set; }
        public string TechnicianRate { get; set; }
        public string Reopen { get; set; }
        public Nullable<System.DateTime> ReopenDate { get; set; }
        public string Worklocation { get; set; }
        public string ReopenReason { get; set; }
        public string DismissedReason { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEIssuesDisposition> TEIssuesDispositions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEIssuesDisposition> TEIssuesDispositions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEIssuesDisposition> TEIssuesDispositions2 { get; set; }
    }
}
