//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TELeadActivityLog
    {
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public int Uniqueid { get; set; }
        public string OldUniqueId { get; set; }
        public string ObjectId { get; set; }
        public Nullable<int> TELead { get; set; }
        public Nullable<int> TEContact { get; set; }
        public Nullable<int> TEOffer { get; set; }
        public Nullable<int> TETask { get; set; }
        public Nullable<int> TEContactModerator { get; set; }
        public Nullable<int> TEContactAttendees { get; set; }
        public string Subject { get; set; }
        public Nullable<System.DateTime> ActivityDate { get; set; }
        public Nullable<System.TimeSpan> ActivityTime { get; set; }
        public Nullable<int> Duration { get; set; }
        public string ActivityDescription { get; set; }
        public string StatusFrom { get; set; }
        public string StatusTo { get; set; }
        public string StatusChangedDesc { get; set; }
        public Nullable<int> Aging { get; set; }
    
        public virtual TEContact TEContact1 { get; set; }
        public virtual TEContact TEContact2 { get; set; }
        public virtual TEContact TEContact3 { get; set; }
        public virtual TEContact TEContact4 { get; set; }
        public virtual TEContact TEContact5 { get; set; }
        public virtual TEContact TEContact6 { get; set; }
        public virtual TEContact TEContact7 { get; set; }
        public virtual TEContact TEContact8 { get; set; }
        public virtual TEContact TEContact9 { get; set; }
        public virtual TEContact TEContact10 { get; set; }
        public virtual TEContact TEContact11 { get; set; }
        public virtual TEContact TEContact12 { get; set; }
        public virtual TEContact TEContact13 { get; set; }
        public virtual TEContact TEContact14 { get; set; }
        public virtual TEContact TEContact15 { get; set; }
        public virtual TEContact TEContact16 { get; set; }
        public virtual TEContact TEContact17 { get; set; }
        public virtual TEContact TEContact18 { get; set; }
        public virtual TEContact TEContact19 { get; set; }
        public virtual TEContact TEContact20 { get; set; }
        public virtual TEContact TEContact21 { get; set; }
        public virtual TEContact TEContact22 { get; set; }
        public virtual TEContact TEContact23 { get; set; }
        public virtual TEContact TEContact24 { get; set; }
        public virtual TEContact TEContact25 { get; set; }
        public virtual TEContact TEContact26 { get; set; }
        public virtual TEContact TEContact27 { get; set; }
        public virtual TEContact TEContact28 { get; set; }
        public virtual TEContact TEContact29 { get; set; }
        public virtual TEContact TEContact30 { get; set; }
        public virtual TEContact TEContact31 { get; set; }
        public virtual TEContact TEContact32 { get; set; }
        public virtual TEContact TEContact33 { get; set; }
        public virtual TEContact TEContact34 { get; set; }
        public virtual TEContact TEContact35 { get; set; }
        public virtual TEContact TEContact36 { get; set; }
        public virtual TEContact TEContact37 { get; set; }
        public virtual TEContact TEContact38 { get; set; }
        public virtual TEContact TEContact39 { get; set; }
        public virtual TEContact TEContact40 { get; set; }
        public virtual TEContact TEContact41 { get; set; }
        public virtual TEContact TEContact42 { get; set; }
    }
}
