//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMIR4_Vendor_Item_PO
    {
        public string CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string LastModifiedOn { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public int Uniqueid { get; set; }
        public string OldUniqueid { get; set; }
        public string Objectid { get; set; }
        public string Vendor_Account_Number { get; set; }
        public string Fugue_Reference_ID { get; set; }
        public string Document_Invoice_Item { get; set; }
        public string Document_Amount { get; set; }
        public string Quantity { get; set; }
        public string Unit_Measure { get; set; }
        public string Purchasing_Document_Number { get; set; }
        public string Purchasing_Item_Number { get; set; }
        public string Document_Reference { get; set; }
        public string Tax_Sales_Purchases_Code { get; set; }
        public string Status { get; set; }
        public string ApprovedBy { get; set; }
        public string ApprovedOn { get; set; }
        public string Document_Accounting_Number { get; set; }
        public string Fiscal_Year { get; set; }
        public string Item_Text { get; set; }
    }
}
