//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMIR4_Vendor_Header
    {
        public string CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string LastModifiedOn { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public int Uniqueid { get; set; }
        public string OldUniqueid { get; set; }
        public string Objectid { get; set; }
        public string Vendor_Account_Number { get; set; }
        public string Fugue_Reference_ID { get; set; }
        public string Document_Accounting_Number { get; set; }
        public string Fiscal_Year { get; set; }
        public string Company_Code { get; set; }
        public string Transactio_Type { get; set; }
        public string Document_Date { get; set; }
        public string Document_Posting_Date { get; set; }
        public string Document_Reference_Number { get; set; }
        public string Document_Amount { get; set; }
        public string Currency_Key { get; set; }
        public string Automatically_Tax_Calculate { get; set; }
        public string Document_Tax_Amount { get; set; }
        public string Tax_Sales_PurchasesCode { get; set; }
        public string Business_Place { get; set; }
        public string Section_Code { get; set; }
        public string Item_Text { get; set; }
        public string Baseline_Due_Date_Calculation { get; set; }
        public string Net_Payment_Due_Date { get; set; }
        public string Unplanned_Delivery_Costs { get; set; }
        public string Exchange_Rate { get; set; }
        public string Document_Type { get; set; }
        public string Assignment_Number { get; set; }
        public string Header_Text { get; set; }
        public string Tax_Amount { get; set; }
        public string Tax_Code { get; set; }
        public string Withholding_Tax_Code { get; set; }
        public string Withholding_Tax_Base_Amount { get; set; }
        public string Withholding_TaxExempt_Amount { get; set; }
        public string Status { get; set; }
        public string ApprovedBy { get; set; }
        public string ApprovedOn { get; set; }
        public string WTCode_QSSKZ1 { get; set; }
        public string WTCode_QSSKZ2 { get; set; }
        public string WTCode_QSSKZ3 { get; set; }
        public string WTCode_QSSHB { get; set; }
        public string WTCode_QSFBT { get; set; }
        public string Terms_PaymentKey { get; set; }
        public string WTCode_QSSHB1 { get; set; }
        public string WTCode_QSFBT1 { get; set; }
    }
}
