//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMobileEligibility
    {
        public int Uniqueid { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> SubmittedOn { get; set; }
        public string SubmittedBy { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
        public string ApprovedBy { get; set; }
        public bool IsDeleted { get; set; }
        public string Status { get; set; }
        public string Type { get; set; }
        public Nullable<int> BandName { get; set; }
        public Nullable<int> TEWorkDesignation { get; set; }
        public Nullable<decimal> MonthlyEligibility { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<int> TECompanies { get; set; }
        public Nullable<int> TESubFunctions { get; set; }
    
        public virtual TECompany TECompany { get; set; }
        public virtual TECompany TECompany1 { get; set; }
        public virtual TECompany TECompany2 { get; set; }
        public virtual TECompany TECompany3 { get; set; }
        public virtual TECompany TECompany4 { get; set; }
        public virtual TESubFunction TESubFunction { get; set; }
        public virtual TESubFunction TESubFunction1 { get; set; }
        public virtual TESubFunction TESubFunction2 { get; set; }
        public virtual TESubFunction TESubFunction3 { get; set; }
        public virtual TESubFunction TESubFunction4 { get; set; }
        public virtual TEWorkingDesignation TEWorkingDesignation { get; set; }
        public virtual TEWorkingDesignation TEWorkingDesignation1 { get; set; }
        public virtual TEWorkingDesignation TEWorkingDesignation2 { get; set; }
        public virtual TEWorkingDesignation TEWorkingDesignation3 { get; set; }
        public virtual TEWorkingDesignation TEWorkingDesignation4 { get; set; }
    }
}
