//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEOfferApprovalCheck
    {
        public int UniqueId { get; set; }
        public Nullable<int> OfferId { get; set; }
        public Nullable<bool> IsDiscount { get; set; }
        public Nullable<bool> IsDiscountApproved { get; set; }
        public Nullable<bool> IsSpecialCondition { get; set; }
        public Nullable<bool> IsSplCondApproved { get; set; }
        public Nullable<bool> IsDPI { get; set; }
        public Nullable<bool> IsDPIApproved { get; set; }
        public Nullable<bool> IsHOOffer { get; set; }
        public Nullable<bool> IsHOApproved { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
    }
}
