//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEOrderPaymentSchedule
    {
        public int OrderPaymentScheduleID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> TowerID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> ScheduleID { get; set; }
        public Nullable<System.DateTime> BaseLinedDate { get; set; }
        public Nullable<System.DateTime> ScheduledDate { get; set; }
        public string RevenueType { get; set; }
        public string MileStoneTypeID { get; set; }
        public string MileStoneInterval { get; set; }
        public Nullable<decimal> RevenueValue { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> LostModifiedBy { get; set; }
        public Nullable<System.DateTime> LostModifiedDate { get; set; }
        public string OldUniqueID { get; set; }
    
        public virtual TEScheduleMaster TEScheduleMaster { get; set; }
    }
}
