//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEPayRollLeaveReport
    {
        public string Createdby { get; set; }
        public Nullable<System.DateTime> Createdon { get; set; }
        public int LeaveReportID { get; set; }
        public Nullable<int> PayrollInputFileID { get; set; }
        public Nullable<int> Teempbasicinfo { get; set; }
        public string EmpCode { get; set; }
        public string EmployeeName { get; set; }
        public string LegalEntity { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<decimal> NoofLeavesTaken { get; set; }
        public Nullable<int> LeaveTypeID { get; set; }
        public string LeaveType { get; set; }
        public string Status { get; set; }
        public bool Isdeleted { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedon { get; set; }
    
        public virtual TEEmpBasicInfo TEEmpBasicInfo1 { get; set; }
        public virtual TEPayRollInputFile TEPayRollInputFile { get; set; }
    }
}
