//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEPayRollReportingPeriod
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TEPayRollReportingPeriod()
        {
            this.TEPayRollInputFiles = new HashSet<TEPayRollInputFile>();
        }
    
        public string Createdby { get; set; }
        public Nullable<System.DateTime> Createdon { get; set; }
        public int ReportingPeriodID { get; set; }
        public Nullable<int> FinancialYearID { get; set; }
        public string PayrollMonth { get; set; }
        public Nullable<System.DateTime> ReportFromDate { get; set; }
        public Nullable<System.DateTime> ReporttoDate { get; set; }
        public string Status { get; set; }
        public bool Isdeleted { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedon { get; set; }
        public Nullable<decimal> version { get; set; }
    
        public virtual TEPayRollFinancialYear TEPayRollFinancialYear { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEPayRollInputFile> TEPayRollInputFiles { get; set; }
    }
}
