//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEPOApprovalCondition
    {
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public string LastModifiedBy { get; set; }
        public bool IsDeleted { get; set; }
        public string ObjectId { get; set; }
        public string OldUniqueId { get; set; }
        public int UniqueId { get; set; }
        public Nullable<int> FundCenter { get; set; }
        public Nullable<int> PurchasingGroup { get; set; }
        public Nullable<int> OrderType { get; set; }
        public Nullable<double> MinAmount { get; set; }
        public Nullable<double> MaxAmount { get; set; }
    }
}
