//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEProjects_HistoryAudit
    {
        public int TRID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public string ProjectName { get; set; }
        public string ProjectCode { get; set; }
        public string ProjectShortName { get; set; }
        public string Logo { get; set; }
        public Nullable<bool> IsSales { get; set; }
        public Nullable<bool> IsMaintenance { get; set; }
        public string LayoutID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string OldLastModifiedby { get; set; }
        public Nullable<System.DateTime> OldLastModifiedDate { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string ProjectColor { get; set; }
        public string Location { get; set; }
        public string LastModifiedby { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> LastModifiedBy_Id { get; set; }
        public string OldUniqueID { get; set; }
        public string SapCode { get; set; }
        public Nullable<int> StateID { get; set; }
        public Nullable<int> TermSheetDesignType { get; set; }
    }
}
