//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEProductSpecification
    {
        public int ProductSpecificationID { get; set; }
        public Nullable<int> ProjectProductID { get; set; }
        public Nullable<int> SpecificationLibraryItemID { get; set; }
        public string ApplicableSpecification { get; set; }
        public string RevisionID { get; set; }
        public string SpecificationBookID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> LostModifiedBy { get; set; }
        public Nullable<System.DateTime> LostModifiedDate { get; set; }
        public string OldUniqueID { get; set; }
        public Nullable<int> SeqNo { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual TESpecificationLibrary TESpecificationLibrary { get; set; }
        public virtual TESubProductDetail TESubProductDetail { get; set; }
    }
}
