//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEProductSpecMapping
    {
        public int MappingID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> SpecificationID { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
    }
}
