//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEPriceBook
    {
        public int PriceBookID { get; set; }
        public string PriceBookName { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> ProjectProductID { get; set; }
        public Nullable<int> TowerID { get; set; }
        public Nullable<int> SchemeID { get; set; }
        public Nullable<int> Specification { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public string OldUniqueID { get; set; }
        public string Status { get; set; }
        public Nullable<int> VersionNo { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> SampleUnitID { get; set; }
    }
}
