//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEPurchase_Item_Structure
    {
        public string CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string LastModifiedOn { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public int Uniqueid { get; set; }
        public string OldUniqueid { get; set; }
        public string Objectid { get; set; }
        public string Purchasing_Order_Number { get; set; }
        public string Item_Number { get; set; }
        public string Assignment_Category { get; set; }
        public string Item_Category { get; set; }
        public string Material_Number { get; set; }
        public string Short_Text { get; set; }
        public string Long_Text { get; set; }
        public string Line_item { get; set; }
        public string Order_Qty { get; set; }
        public string Unit_Measure { get; set; }
        public string Delivery_Date { get; set; }
        public string Net_Price { get; set; }
        public string Material_Group { get; set; }
        public string Plant { get; set; }
        public string Storage_Location { get; set; }
        public string Requirement_Tracking_Number { get; set; }
        public string Requisition_Number { get; set; }
        public string Item_Purchase_Requisition { get; set; }
        public string Returns_Item { get; set; }
        public string Tax_salespurchases_code { get; set; }
        public string Overall_limit { get; set; }
        public string Expected_Value { get; set; }
        public string Total_Value { get; set; }
        public string No_Limit { get; set; }
        public string Overdelivery_Tolerance { get; set; }
        public string Underdelivery_Tolerance { get; set; }
        public string Status { get; set; }
        public string ApprovedBy { get; set; }
        public string ApprovedOn { get; set; }
        public string Version { get; set; }
        public string teversion { get; set; }
        public Nullable<int> POStructureId { get; set; }
        public string HSNCode { get; set; }
    }
}
