//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEPurchase_Annexure_OtherCharges
    {
        public string CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string LastModifiedOn { get; set; }
        public string LastModifiedBy { get; set; }
        public bool IsDeleted { get; set; }
        public string Status { get; set; }
        public int OtherChargesId { get; set; }
        public string PurchasingOrderNumber { get; set; }
        public string ItemNumber { get; set; }
        public string LineItemNumber { get; set; }
        public Nullable<int> POStructureId { get; set; }
        public string PackingForwardingCondition { get; set; }
        public string PackingForwardingValue { get; set; }
        public string FreightCondition { get; set; }
        public string FreightValue { get; set; }
        public string OtherServicesType { get; set; }
        public string OtherServicesCondition { get; set; }
        public string OtherServicesValue { get; set; }
    }
}
