//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TESaleTermsANDCondition
    {
        public int TandCID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> MasterTermsandConditionID { get; set; }
        public Nullable<int> SeqNo { get; set; }
        public Nullable<int> Description { get; set; }
        public string IsTEORJD { get; set; }
        public Nullable<int> DocumentType { get; set; }
        public string LaunchType { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public string OldUniqueID { get; set; }
        public string ProductType { get; set; }
        public string Status { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> BlockId { get; set; }
    }
}
