//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEServiceEntryItem
    {
        public int UniqueId { get; set; }
        public int TEServiceEntryID { get; set; }
        public string ServiceSubTitleShortText { get; set; }
        public string ServiceSubTitleLongText { get; set; }
        public string LineItemNumber { get; set; }
        public string ServiceActivityCode { get; set; }
        public Nullable<decimal> PreviousQuantity { get; set; }
        public Nullable<decimal> ReceivedQuantity { get; set; }
        public Nullable<decimal> AcceptedQuantity { get; set; }
        public Nullable<decimal> CummulativeQuantity { get; set; }
        public Nullable<decimal> BalanceQuantity { get; set; }
        public string ItemText { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<decimal> TaxPrice { get; set; }
        public string Status { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<decimal> ContractorMargin { get; set; }
        public string SEItemNumber { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> NetPrice { get; set; }
        public Nullable<decimal> OtherCharges { get; set; }
        public string UOM { get; set; }
        public Nullable<decimal> TaxCode { get; set; }
    
        public virtual TEServiceEntry TEServiceEntry { get; set; }
    }
}
