//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TESGCampaign
    {
        public int UniqueId { get; set; }
        public string CampaignName { get; set; }
        public Nullable<int> SGInviteId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<int> SGCampaignId { get; set; }
        public string Type { get; set; }
        public string Subtype { get; set; }
        public string Status { get; set; }
        public string Uri { get; set; }
        public string Language { get; set; }
        public Nullable<int> TESGSurveyId { get; set; }
    }
}
