//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TESGSurveyContactResponse
    {
        public int UniqueId { get; set; }
        public int ResponseId { get; set; }
        public Nullable<int> QuestionId { get; set; }
        public Nullable<int> OptionId { get; set; }
        public string Comments { get; set; }
        public string OptionValuae { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> CreatedBy { get; set; }
        public Nullable<int> SGSurveyId { get; set; }
        public Nullable<int> SGCampaignId { get; set; }
        public Nullable<int> SGInviteId { get; set; }
        public Nullable<int> ParticipantEmail { get; set; }
    }
}
