//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TESGSurvey
    {
        public int UniqueId { get; set; }
        public string Title { get; set; }
        public string Type { get; set; }
        public string Subtype { get; set; }
        public int SGSurveyId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> Surveyowner { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string Surveystatus { get; set; }
    }
}
