//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TESurveyStatu
    {
        public int UniqueId { get; set; }
        public Nullable<int> EmpUniqueId { get; set; }
        public string EmpCode { get; set; }
        public string SurveyID { get; set; }
        public bool IsServeyTaken { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public string LastModifiedBy { get; set; }
        public string FeedBackTo { get; set; }
        public Nullable<int> LeadershipUniqueId { get; set; }
    
        public virtual TEEmpBasicInfo TEEmpBasicInfo { get; set; }
        public virtual TEEmpBasicInfo TEEmpBasicInfo1 { get; set; }
        public virtual TEEmpBasicInfo TEEmpBasicInfo2 { get; set; }
    }
}
