//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TETargetAllocation
    {
        public int Targetallocation { get; set; }
        public int SalesConsultantId { get; set; }
        public string FinancialYear { get; set; }
        public string FinancialQuarter { get; set; }
        public int ProjectID { get; set; }
        public Nullable<int> TargetedRevenue { get; set; }
        public Nullable<int> TargetedUnits { get; set; }
        public Nullable<int> ActualSalesValues { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public int LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public string OldUniqueID { get; set; }
        public Nullable<int> TargetedCollections { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> Quarter1 { get; set; }
        public Nullable<int> Quarter2 { get; set; }
        public Nullable<int> Quarter3 { get; set; }
        public Nullable<int> Quarter4 { get; set; }
        public Nullable<decimal> AverageUnitCost { get; set; }
        public Nullable<decimal> EMDValue { get; set; }
        public Nullable<decimal> ActualCollectionvalue { get; set; }
    
        public virtual TEProject TEProject { get; set; }
    }
}
