//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TETask
    {
        public int TaskID { get; set; }
        public Nullable<int> ContactID { get; set; }
        public Nullable<int> ContextID { get; set; }
        public string TaskType { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsPrivate { get; set; }
        public Nullable<int> LocationID { get; set; }
        public string Duration { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public string LastModifiedBy { get; set; }
        public string TaskStatus { get; set; }
        public string TaskTitle { get; set; }
        public Nullable<int> ResponsibleConsultant { get; set; }
        public Nullable<int> LastModifiedBy_Id { get; set; }
        public string OldUniqueID { get; set; }
        public Nullable<int> SiteVisit { get; set; }
    
        public virtual TEContact TEContact { get; set; }
    }
}
