//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TETowerMaster_HistoryAudit
    {
        public int TRID { get; set; }
        public Nullable<int> TowerID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public string TowerName { get; set; }
        public string TowerShortName { get; set; }
        public string MaxLevel { get; set; }
        public string Description { get; set; }
        public string LaunchStatus { get; set; }
        public Nullable<bool> OpenForSale { get; set; }
        public string LayOutID { get; set; }
        public Nullable<System.DateTime> CCReportedDate { get; set; }
        public Nullable<System.DateTime> MarketingLaunchDate { get; set; }
        public Nullable<System.DateTime> ProgressEffectiveDate { get; set; }
        public Nullable<System.DateTime> ExpectedCompletionDate { get; set; }
        public string CurrentCompletionPercentage { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public string OldLastModifiedBy { get; set; }
        public Nullable<System.DateTime> OldLastModifiedDate { get; set; }
        public Nullable<int> LastModifiedBy_Id { get; set; }
        public string OldUniqueID { get; set; }
        public Nullable<int> BlockId { get; set; }
        public string CompletionPercentageCertificate { get; set; }
        public Nullable<System.DateTime> OCCompletionDate { get; set; }
        public Nullable<decimal> Rera_Saleable_Area { get; set; }
        public Nullable<decimal> Outdoor_Area { get; set; }
        public Nullable<decimal> RERA_Carpet_Area { get; set; }
    }
}
