//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEUserProfile
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string House_no { get; set; }
        public string Street1 { get; set; }
        public string Street2 { get; set; }
        public string Area { get; set; }
        public string City { get; set; }
        public Nullable<int> Pincode { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public Nullable<bool> Status { get; set; }
        public string AndroidToken { get; set; }
        public string IosToken { get; set; }
        public string Password { get; set; }
        public string Facebookid { get; set; }
        public string GoogleID { get; set; }
        public string CallName { get; set; }
        public string Photo { get; set; }
        public Nullable<int> RoleID { get; set; }
        public string BizAppID { get; set; }
        public string CallCentreID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> LastModifiedBy_Id { get; set; }
        public string OldUniqueID { get; set; }
    }
}
