//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEUserSalesEngineMapping
    {
        public int UserId { get; set; }
        public Nullable<int> TEProject { get; set; }
        public string SalesEngine { get; set; }
        public Nullable<bool> IsAdditionalSC { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
