//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEWorkLocation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TEWorkLocation()
        {
            this.TEAssestRequestations = new HashSet<TEAssestRequestation>();
            this.TEAssestRequestations1 = new HashSet<TEAssestRequestation>();
            this.TEAssestRequestations2 = new HashSet<TEAssestRequestation>();
            this.TEAssetAllocations = new HashSet<TEAssetAllocation>();
            this.TEAssetAllocations1 = new HashSet<TEAssetAllocation>();
            this.TEAssetAllocations2 = new HashSet<TEAssetAllocation>();
            this.TEAssetLosses = new HashSet<TEAssetLoss>();
            this.TEAssetLosses1 = new HashSet<TEAssetLoss>();
            this.TEAssetLosses2 = new HashSet<TEAssetLoss>();
            this.TEClearanceMasters = new HashSet<TEClearanceMaster>();
            this.TEClearanceMasters1 = new HashSet<TEClearanceMaster>();
            this.TEClearanceMasters2 = new HashSet<TEClearanceMaster>();
            this.TEEmpAssignmentDetails = new HashSet<TEEmpAssignmentDetail>();
            this.TEEmpAssignmentDetails1 = new HashSet<TEEmpAssignmentDetail>();
            this.TEEmpAssignmentDetails2 = new HashSet<TEEmpAssignmentDetail>();
            this.TEEmpAssignmentDetails3 = new HashSet<TEEmpAssignmentDetail>();
            this.TEHoliday_TEWorkLocation_Mappings = new HashSet<TEHoliday_TEWorkLocation_Mappings>();
            this.TEHoliday_TEWorkLocation_Mappings1 = new HashSet<TEHoliday_TEWorkLocation_Mappings>();
            this.TEHoliday_TEWorkLocation_Mappings2 = new HashSet<TEHoliday_TEWorkLocation_Mappings>();
        }
    
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public int Uniqueid { get; set; }
        public string OldUniqueid { get; set; }
        public string Objectid { get; set; }
        public string WorkLocationName { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
        public string Mobile { get; set; }
        public string Landline { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
        public string Status { get; set; }
        public string Coordinates { get; set; }
        public string State { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEAssestRequestation> TEAssestRequestations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEAssestRequestation> TEAssestRequestations1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEAssestRequestation> TEAssestRequestations2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEAssetAllocation> TEAssetAllocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEAssetAllocation> TEAssetAllocations1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEAssetAllocation> TEAssetAllocations2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEAssetLoss> TEAssetLosses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEAssetLoss> TEAssetLosses1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEAssetLoss> TEAssetLosses2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEClearanceMaster> TEClearanceMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEClearanceMaster> TEClearanceMasters1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEClearanceMaster> TEClearanceMasters2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEmpAssignmentDetail> TEEmpAssignmentDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEmpAssignmentDetail> TEEmpAssignmentDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEmpAssignmentDetail> TEEmpAssignmentDetails2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEEmpAssignmentDetail> TEEmpAssignmentDetails3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEHoliday_TEWorkLocation_Mappings> TEHoliday_TEWorkLocation_Mappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEHoliday_TEWorkLocation_Mappings> TEHoliday_TEWorkLocation_Mappings1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEHoliday_TEWorkLocation_Mappings> TEHoliday_TEWorkLocation_Mappings2 { get; set; }
    }
}
