//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitorFeedbackSummary
    {
        public int VisitorID { get; set; }
        public string DetailedFeedback { get; set; }
        public string SalesConsultantComments { get; set; }
        public Nullable<System.DateTime> FeedbackDatetime { get; set; }
        public int ID { get; set; }
    }
}
