//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WBSMASTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WBSMASTER()
        {
            this.EBUILDPRICINGs = new HashSet<EBUILDPRICING>();
            this.RATEMASTERPRICINGs = new HashSet<RATEMASTERPRICING>();
            this.RATEMASTERPRICINGs1 = new HashSet<RATEMASTERPRICING>();
        }
    
        public int WBSID { get; set; }
        public string WBSCODE { get; set; }
        public string SPACECODE { get; set; }
        public string DESIGNCODE { get; set; }
        public string UNI { get; set; }
        public string LEVEL1 { get; set; }
        public string LEVEL2 { get; set; }
        public string LEVEL3 { get; set; }
        public string LEVEL4 { get; set; }
        public string LEVEL5 { get; set; }
        public string LEVEL6 { get; set; }
        public string LEVEL7 { get; set; }
        public Nullable<int> QUANTITY { get; set; }
        public string UOM { get; set; }
        public string DESCRIPTION { get; set; }
        public string MAKE { get; set; }
        public string SERIES { get; set; }
        public string FINISH { get; set; }
        public string PROCUREMENTCODE { get; set; }
        public string EBUILDCODE { get; set; }
        public Nullable<int> SUBCATEGORYID { get; set; }
        public string name { get; set; }
        public Nullable<int> categoryid { get; set; }
        public string oldwbscode { get; set; }
        public Nullable<int> isOutOfProduction { get; set; }
        public Nullable<int> parentid { get; set; }
        public string remarks { get; set; }
        public Nullable<decimal> oldrate { get; set; }
    
        public virtual CATEGORYMASTER CATEGORYMASTER { get; set; }
        public virtual CATEGORYMASTER CATEGORYMASTER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EBUILDPRICING> EBUILDPRICINGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RATEMASTERPRICING> RATEMASTERPRICINGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RATEMASTERPRICING> RATEMASTERPRICINGs1 { get; set; }
        public virtual SUBCATEGORYMASTER SUBCATEGORYMASTER { get; set; }
        public virtual SUBCATEGORYMASTER SUBCATEGORYMASTER1 { get; set; }
        public virtual SUBCATEGORYMASTER SUBCATEGORYMASTER2 { get; set; }
    }
}
