//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPRMASTER
    {
        public int CPRID { get; set; }
        public decimal VALUE { get; set; }
        public string TAG { get; set; }
        public string REMARKS { get; set; }
        public string CREATEDBY { get; set; }
        public System.DateTime CREATEDDATE { get; set; }
        public string APPROVEDBY { get; set; }
        public Nullable<System.DateTime> APPROVEDDATE { get; set; }
        public string STATUS { get; set; }
        public Nullable<int> isDeleted { get; set; }
    }
}
