//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JDPriceBook
    {
        public int JDPriceBookID { get; set; }
        public string JDPriceBookName { get; set; }
        public Nullable<int> ProjectShareID { get; set; }
        public Nullable<int> UnitShareID { get; set; }
        public Nullable<int> SchemeID { get; set; }
        public Nullable<int> Specification { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
    }
}
