//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POMasterApprover
    {
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public string LastModifiedBy { get; set; }
        public bool IsDeleted { get; set; }
        public string ObjectId { get; set; }
        public string OldUniqueId { get; set; }
        public int UniqueId { get; set; }
        public Nullable<int> SequenceId { get; set; }
        public int ApproverId { get; set; }
        public string Type { get; set; }
        public Nullable<int> ApprovalConditionId { get; set; }
        public string ApproverName { get; set; }
    }
}
