//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRICEPUSHDETAIL
    {
        public int PRICEPUSHID { get; set; }
        public string PRICEBOOKID { get; set; }
        public string PUSHEDBY { get; set; }
        public Nullable<System.DateTime> PUSHEDON { get; set; }
        public string SERVERNAME { get; set; }
        public string PROJECTNAME { get; set; }
        public string STATUS { get; set; }
        public string SOURCEIP { get; set; }
    }
}
