//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class R_TEEmailMessage_TEEdmTemplate
    {
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public string LastModifiedBy { get; set; }
        public string ObjectId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public int UniqueId { get; set; }
        public Nullable<int> TEEdmTempalateId { get; set; }
        public Nullable<int> TotalSent { get; set; }
        public Nullable<int> Delivered { get; set; }
        public Nullable<int> Bounced { get; set; }
        public Nullable<int> Opened { get; set; }
        public Nullable<int> Clicked { get; set; }
        public Nullable<int> Unsubscribed { get; set; }
        public Nullable<int> Dropped { get; set; }
        public Nullable<int> Spams { get; set; }
        public Nullable<int> TEEmailMessage { get; set; }
    }
}
