//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class R_TERelationshipsOfContact
    {
        public int UniqueId { get; set; }
        public Nullable<int> TEContact { get; set; }
        public Nullable<int> TERelationshipCategory { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Status { get; set; }
        public string ApprovedBy { get; set; }
        public string ApprovedOn { get; set; }
        public Nullable<bool> IsPotential { get; set; }
        public string Importance { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<double> InflowValue { get; set; }
        public Nullable<double> OutflowValue { get; set; }
    }
}
