//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TE_Customer_Templates
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TE_Customer_Templates()
        {
            this.TEDeedOfCancellationDates = new HashSet<TEDeedOfCancellationDate>();
            this.TEHandoverDates = new HashSet<TEHandoverDate>();
        }
    
        public int CustomerTemplateID { get; set; }
        public string SAPCustomerID { get; set; }
        public int OfferId { get; set; }
        public string DocumentName { get; set; }
        public int DocumentType { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int Version { get; set; }
        public string Status { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> RefProjectTemplateID { get; set; }
        public Nullable<int> UnSignedDMSID { get; set; }
        public Nullable<int> SignedDMSID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEDeedOfCancellationDate> TEDeedOfCancellationDates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEHandoverDate> TEHandoverDates { get; set; }
    }
}
