//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TE_Document_Templates
    {
        public int TemplateID { get; set; }
        public string DocumentName { get; set; }
        public Nullable<int> Version { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public Nullable<int> TemplateTypeId { get; set; }
        public string TemplateContent { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<int> RefDocumentTypeID { get; set; }
    }
}
