//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEApplicantIdentityDetail
    {
        public int ApplicantIdentityDetailsID { get; set; }
        public Nullable<int> ApplicantID { get; set; }
        public Nullable<int> ContactID { get; set; }
        public string Profession { get; set; }
        public string Industry { get; set; }
        public string Company { get; set; }
        public string Designation { get; set; }
        public string IdentityProfType { get; set; }
        public string IndentityProfNumber { get; set; }
        public Nullable<System.DateTime> DateOfIssue { get; set; }
        public Nullable<int> IdentityProfAttachment { get; set; }
        public string AddressProfType { get; set; }
        public Nullable<int> AddressProfAttachment { get; set; }
        public string PanNumber { get; set; }
        public Nullable<int> PanAttachment { get; set; }
        public string AadharNumber { get; set; }
        public Nullable<int> AadharAttachment { get; set; }
        public Nullable<System.DateTime> AadharIsssueDate { get; set; }
        public Nullable<System.DateTime> AadharValidityDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
