//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEBankDetails_HistoryAudit
    {
        public int TRID { get; set; }
        public Nullable<int> BankDetailsID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public string TowerID { get; set; }
        public string CollectionType { get; set; }
        public string AccountName { get; set; }
        public string AccountNumber { get; set; }
        public string BankCategory { get; set; }
        public string BankName { get; set; }
        public string City { get; set; }
        public string BranchName { get; set; }
        public string MICRCode { get; set; }
        public string IFSCSWiftCode { get; set; }
        public string SwiftCode { get; set; }
        public string SapBankCode { get; set; }
        public string Type { get; set; }
        public string BankAddress { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> OldLastModifiedBy { get; set; }
        public Nullable<System.DateTime> OldLastModifiedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public string OldUniqueID { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> BusinessPartnerId { get; set; }
    }
}
