//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEBPLeadsStaging
    {
        public int BPLeadsStagingID { get; set; }
        public Nullable<int> TEBPRefID { get; set; }
        public Nullable<int> ContactID { get; set; }
        public string Salutation { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Organization { get; set; }
        public string Designation { get; set; }
        public string Address { get; set; }
        public string AreaOrCityOrCountry { get; set; }
        public Nullable<int> FirstConnect { get; set; }
        public Nullable<int> FirstConnectMode { get; set; }
        public Nullable<int> SalesEngine { get; set; }
        public string CityChoice { get; set; }
        public string PreferredLocation { get; set; }
        public string InterstedProject { get; set; }
        public Nullable<int> PreferredProjects { get; set; }
        public Nullable<int> Product { get; set; }
        public string Specification { get; set; }
        public string Notes { get; set; }
        public string status { get; set; }
        public Nullable<int> OTP { get; set; }
        public Nullable<int> TELeadId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public Nullable<int> LastModifiedById { get; set; }
    }
}
