//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEBusinessPartnersRepresentative
    {
        public int BPRepresentativeID { get; set; }
        public int BusinessPartnerID { get; set; }
        public Nullable<int> RepresentativeCompanyContact_ID { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> LastModifiedBy_Id { get; set; }
        public string OldUniqueID { get; set; }
        public string FileType { get; set; }
        public string Path { get; set; }
        public Nullable<int> DMSDocumentId { get; set; }
    
        public virtual TEBusinessPartner TEBusinessPartner { get; set; }
    }
}
