//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEBusinessPartnerB2CAccountDetails
    {
        public int BPB2CAccountDtlsId { get; set; }
        public int BusinessPartnerId { get; set; }
        public string BPName { get; set; }
        public string BPEmailId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedSourceProcess { get; set; }
        public bool IsB2CAccountCreated { get; set; }
        public Nullable<System.DateTime> B2CAccountCreatedOn { get; set; }
        public string B2CAccountCreatedSourceProcess { get; set; }
        public string B2CAccountObjectId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> LastModifiedById { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
    }
}
