//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TECarParksMaster_HistoryAudit
    {
        public int TRID { get; set; }
        public Nullable<int> CarParkMasterID { get; set; }
        public string CarParkShortName { get; set; }
        public string CarParkDimension { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public string OldLastModifiedBy { get; set; }
        public Nullable<System.DateTime> OldLastModifiedDate { get; set; }
        public Nullable<int> LastModifiedBy_Id { get; set; }
        public string OldUniqueID { get; set; }
        public string CarParkCode { get; set; }
        public Nullable<int> CarParkPrice { get; set; }
    }
}
