//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TECancellationBreakup
    {
        public int CBID { get; set; }
        public string SAPReferenceID { get; set; }
        public Nullable<int> OfferID { get; set; }
        public string InstallmentName { get; set; }
        public Nullable<System.DateTime> InstallmentDate { get; set; }
        public string PaymentType { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Status { get; set; }
        public Nullable<int> LastModifedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public string Comments { get; set; }
        public Nullable<int> CancellationID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
