//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TECollateral
    {
        public string UploadedBy { get; set; }
        public System.DateTime UploadedOn { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public int CollateralID { get; set; }
        public string OldUniqueid { get; set; }
        public Nullable<int> DMSDocumentId { get; set; }
        public string DocumentTitle { get; set; }
        public Nullable<int> DocumentCategoryID { get; set; }
        public Nullable<int> DocumentTypeID { get; set; }
        public Nullable<int> DocumentSubTypeID { get; set; }
        public Nullable<int> ProjectProductID { get; set; }
        public Nullable<int> ProjectProductTypeID { get; set; }
        public string Description { get; set; }
        public string Path { get; set; }
        public string FileType { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> VersionNo { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public string ReferenceName { get; set; }
    }
}
