//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEContactProfession
    {
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public string LastModifiedBy { get; set; }
        public bool IsDeleted { get; set; }
        public int Uniqueid { get; set; }
        public string OldUniqueid { get; set; }
        public string Objectid { get; set; }
        public string Profession { get; set; }
        public string Organisation { get; set; }
        public string Type { get; set; }
        public Nullable<int> TEContact { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
        public Nullable<int> TEContactOrganisation { get; set; }
        public string Department { get; set; }
        public string Industry { get; set; }
    
        public virtual TEContact TEContact1 { get; set; }
        public virtual TEContactOrganisation TEContactOrganisation1 { get; set; }
    }
}
