//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEDCBreakUp
    {
        public int DCBID { get; set; }
        public Nullable<int> DCID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> ProjectedDate { get; set; }
        public string InstallmentID { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> LastModifiedById { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public string SAPDocumentID { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public Nullable<int> PaymentMode { get; set; }
        public string PaidTo { get; set; }
        public string Remarks { get; set; }
    }
}
