//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEEDesignEmployeeSync
    {
        public int UniqueID { get; set; }
        public int ProjectID { get; set; }
        public string ProjectName { get; set; }
        public string ProjectCode { get; set; }
        public int EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public string EmailID { get; set; }
        public string AuthKey { get; set; }
        public Nullable<int> OrganisationRuleID { get; set; }
        public Nullable<int> SyncBy { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
        public Nullable<bool> SyncStatus { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
