//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEEmpNotification
    {
        public int NotificationID { get; set; }
        public string Module { get; set; }
        public string Message { get; set; }
        public Nullable<int> SentTo { get; set; }
        public Nullable<int> SentFrom { get; set; }
        public Nullable<System.DateTime> SentOn { get; set; }
        public Nullable<bool> IsRead { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifedOn { get; set; }
        public string NotificationType { get; set; }
        public Nullable<System.DateTime> ValidTillDate { get; set; }
    }
}
