//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEEmpBasicInfo
    {
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public string LastModifiedBy { get; set; }
        public bool IsDeleted { get; set; }
        public int Uniqueid { get; set; }
        public string OldUniqueid { get; set; }
        public string Objectid { get; set; }
        public string EmployeeId { get; set; }
        public string UserId { get; set; }
        public string TEUser { get; set; }
        public string Salutation { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string RelationOf { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Gender { get; set; }
        public string MaritalStatus { get; set; }
        public Nullable<System.DateTime> DateOfMarriage { get; set; }
        public string LandlineNo { get; set; }
        public string Mobile { get; set; }
        public string PersonalEmail { get; set; }
        public string OfficialEmail { get; set; }
        public string BloodGroup { get; set; }
        public string Photo { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public Nullable<System.DateTime> DateOfConfirmation { get; set; }
        public Nullable<decimal> TEExperience { get; set; }
        public Nullable<decimal> PrevExperience { get; set; }
        public Nullable<decimal> TotalExperience { get; set; }
        public Nullable<System.DateTime> ProposedDOJ { get; set; }
        public Nullable<System.DateTime> ProposedDOL { get; set; }
        public Nullable<System.DateTime> DOL { get; set; }
        public string Reason { get; set; }
        public string Citizenship { get; set; }
        public string ResidentStatus { get; set; }
        public string TETag { get; set; }
    }
}
