//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEException
    {
        public int TRID { get; set; }
        public string ModuleName { get; set; }
        public string ExceptionString { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModiffiedDate { get; set; }
        public string OldUniqueID { get; set; }
    }
}
