//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEInvoiceCreditNote
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TEInvoiceCreditNote()
        {
            this.TEInvoiceCreditNoteBreakUps = new HashSet<TEInvoiceCreditNoteBreakUp>();
        }
    
        public int InvoiceCreditNoteID { get; set; }
        public Nullable<int> InVoiceID { get; set; }
        public string InvoiceName { get; set; }
        public Nullable<decimal> TotalInvoiceAmount { get; set; }
        public string SAPInVoiceID { get; set; }
        public Nullable<System.DateTime> InVoicedOn { get; set; }
        public Nullable<decimal> InvoiceConsideration { get; set; }
        public string SAPCustomerID { get; set; }
        public string InvoiceType { get; set; }
        public string InvoiceSAPRefDocumentNo { get; set; }
        public Nullable<decimal> TowardsLand { get; set; }
        public Nullable<decimal> TowardsConstruction { get; set; }
        public Nullable<decimal> TowardsMaintainance { get; set; }
        public Nullable<decimal> TowardsOthers { get; set; }
        public Nullable<decimal> TowardsReimbursement { get; set; }
        public Nullable<decimal> TowardsCustomisation { get; set; }
        public Nullable<decimal> TowardsHomeImprovement { get; set; }
        public Nullable<decimal> TowardsRST { get; set; }
        public Nullable<decimal> TowardsRVAT { get; set; }
        public Nullable<decimal> TowardsRSBC { get; set; }
        public Nullable<decimal> TowardsRKKC { get; set; }
        public Nullable<decimal> TowardsRCGST { get; set; }
        public Nullable<decimal> TowardsRSGST { get; set; }
        public Nullable<decimal> TowardsInterest { get; set; }
        public string GSTDocumentType { get; set; }
        public string SAPCreditNoteID { get; set; }
        public string SAPCreditNoteRefDocNo { get; set; }
        public Nullable<System.DateTime> InVoiceCancelledOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEInvoiceCreditNoteBreakUp> TEInvoiceCreditNoteBreakUps { get; set; }
    }
}
