//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEInvoice
    {
        public int InVoiceID { get; set; }
        public Nullable<int> ContextID { get; set; }
        public Nullable<System.DateTime> InVoiceDate { get; set; }
        public string InVoiceStatus { get; set; }
        public string SAPInVoiceID { get; set; }
        public string Notes { get; set; }
        public Nullable<int> PreparedBy { get; set; }
        public Nullable<System.DateTime> PreparedOn { get; set; }
        public Nullable<int> InVoicedBy { get; set; }
        public Nullable<System.DateTime> InVoicedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public Nullable<int> LastModifiedBy_Id { get; set; }
        public string OldUniqueID { get; set; }
        public string InvoiceType { get; set; }
        public Nullable<decimal> InvoiceConsideration { get; set; }
        public Nullable<decimal> TotalInvoiceAmount { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public Nullable<int> MileStoneRef { get; set; }
        public Nullable<int> SplittedMileStoneRef { get; set; }
        public string SAPOrderID { get; set; }
        public string SAPCustomerID { get; set; }
        public Nullable<decimal> TowardsLand { get; set; }
        public Nullable<decimal> TowardsConstruction { get; set; }
        public Nullable<decimal> TowardsMaintainance { get; set; }
        public Nullable<decimal> TowardsOthers { get; set; }
        public Nullable<decimal> TowardsReimbursement { get; set; }
        public string PaidStatus { get; set; }
        public Nullable<decimal> TowardsCustomisation { get; set; }
        public Nullable<decimal> TowardsInterest { get; set; }
        public string InvoiceName { get; set; }
        public Nullable<decimal> UnPaidAmount { get; set; }
        public Nullable<decimal> TowardsHomeImprovement { get; set; }
        public Nullable<decimal> TowardsRST { get; set; }
        public Nullable<decimal> TowardsRVAT { get; set; }
        public Nullable<decimal> TowardsRSBC { get; set; }
        public Nullable<decimal> TowardsRKKC { get; set; }
        public Nullable<decimal> TowardsRCGST { get; set; }
        public Nullable<decimal> TowardsRSGST { get; set; }
        public Nullable<bool> IsDispatched { get; set; }
        public string SAPRefDocumentNo { get; set; }
    }
}
