//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEIncrementalSchemePriceBook
    {
        public int TEIncSchemePBID { get; set; }
        public int ProjectID { get; set; }
        public int SpecificationID { get; set; }
        public int ProductID { get; set; }
        public int SchemeID { get; set; }
        public decimal IncrementalSchemeRate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public int VersionNo { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> TowerID { get; set; }
        public string Status { get; set; }
    }
}
