//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEOffer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TEOffer()
        {
            this.TECancellations = new HashSet<TECancellation>();
            this.TECarParks = new HashSet<TECarPark>();
            this.TEChangeOrders = new HashSet<TEChangeOrder>();
            this.TEOfferSchemes = new HashSet<TEOfferScheme>();
            this.TEOfferDocuments = new HashSet<TEOfferDocument>();
            this.TEOfferExpireExtensions = new HashSet<TEOfferExpireExtension>();
            this.TEOfferMileStones = new HashSet<TEOfferMileStone>();
            this.TEOfferPriceBreakUpDetails = new HashSet<TEOfferPriceBreakUpDetail>();
            this.TEOfferSpecialConditions = new HashSet<TEOfferSpecialCondition>();
            this.TEOfferSpecifications = new HashSet<TEOfferSpecification>();
            this.TEOfferTCs = new HashSet<TEOfferTC>();
        }
    
        public int OfferID { get; set; }
        public Nullable<int> LeadID { get; set; }
        public string OfferTitleName { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> UnitID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> SpecsType { get; set; }
        public Nullable<decimal> CarPetArea { get; set; }
        public Nullable<decimal> BuiltUpArea { get; set; }
        public Nullable<decimal> StandardPlotArea { get; set; }
        public Nullable<decimal> SuperBuiltUpArea { get; set; }
        public Nullable<decimal> SaleableArea { get; set; }
        public Nullable<decimal> EffectiveDiscount { get; set; }
        public Nullable<decimal> EffecDiscPercentage { get; set; }
        public Nullable<decimal> DiscOnBasicCost { get; set; }
        public Nullable<decimal> DiscPaymentTerms { get; set; }
        public Nullable<decimal> DiscSpecialConditions { get; set; }
        public string DPIIncentiveApplicable { get; set; }
        public string PreparedBy { get; set; }
        public Nullable<int> SubmittedBy { get; set; }
        public Nullable<int> ConnectSalesConsultant { get; set; }
        public Nullable<int> CloseSalesConsultant { get; set; }
        public Nullable<int> AssistedSalesConsultant { get; set; }
        public Nullable<int> CEMmanager { get; set; }
        public Nullable<int> RevisionNo { get; set; }
        public string CurrentStatus { get; set; }
        public string OrderStatus { get; set; }
        public string TransitionStatus { get; set; }
        public string OfferCustomerName { get; set; }
        public string MergedUnit { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<int> ExpiredBy { get; set; }
        public Nullable<System.DateTime> CCPSaleTime { get; set; }
        public string SAPCustomerID { get; set; }
        public string SAPOrderID { get; set; }
        public string BusinesSEGMENT { get; set; }
        public Nullable<int> RegisterCommunicationID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public Nullable<int> LastModifiedBy_Id { get; set; }
        public string OldUniqueID { get; set; }
        public Nullable<int> BaseConsideration { get; set; }
        public Nullable<int> Consideration { get; set; }
        public Nullable<decimal> DiscountPercentage { get; set; }
        public Nullable<int> PriceBookId { get; set; }
        public Nullable<bool> IsEMD { get; set; }
        public Nullable<bool> IsTSSigned { get; set; }
        public Nullable<int> LandPrice { get; set; }
        public Nullable<int> ConstructionPrice { get; set; }
        public Nullable<bool> IsManualOffer { get; set; }
        public Nullable<int> SchemeId { get; set; }
        public Nullable<decimal> PriceOfferDiscount { get; set; }
        public Nullable<decimal> UpFrontDiscount { get; set; }
        public Nullable<decimal> DefaultNpvValue { get; set; }
        public string SaleType { get; set; }
        public string SaleOrderClassification { get; set; }
        public string CustomizationOption { get; set; }
        public Nullable<decimal> DefaultNPVpercentage { get; set; }
        public Nullable<decimal> PaybletoOwner { get; set; }
        public Nullable<decimal> PayableToDeveloper { get; set; }
        public Nullable<int> CustomizationStatus { get; set; }
        public Nullable<int> CommonOrderID { get; set; }
        public Nullable<int> IsCustomisation { get; set; }
        public Nullable<bool> isOrderInUse { get; set; }
        public Nullable<int> VersionNo { get; set; }
        public Nullable<decimal> ConstructionComplPercentage { get; set; }
        public Nullable<int> ReImbursementAmount { get; set; }
        public Nullable<decimal> CancellationFee { get; set; }
        public Nullable<decimal> DelayCompensationRate { get; set; }
        public Nullable<decimal> DelayCompensatoinRule { get; set; }
        public Nullable<decimal> TransferOrderFee { get; set; }
        public Nullable<System.DateTime> PromisedHandOverDate { get; set; }
        public Nullable<decimal> JDOwnershipPercentage { get; set; }
        public bool IsPostGSTOrder { get; set; }
        public bool IsFSOAInitiated { get; set; }
        public Nullable<decimal> Outdoor_Area { get; set; }
        public Nullable<decimal> RERA_Carpet_Area { get; set; }
        public Nullable<int> CustomisationManager { get; set; }
        public Nullable<System.DateTime> AgreementDate { get; set; }
        public Nullable<int> AFSStatus { get; set; }
        public string TypeOfOrder { get; set; }
        public string TypeOfSale { get; set; }
        public string Purchaser { get; set; }
        public Nullable<bool> eDesignAccountStatus { get; set; }
        public Nullable<int> CustomisationArchitect { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TECancellation> TECancellations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TECarPark> TECarParks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEChangeOrder> TEChangeOrders { get; set; }
        public virtual TELead TELead { get; set; }
        public virtual TEProject TEProject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEOfferScheme> TEOfferSchemes { get; set; }
        public virtual TEPriceBook TEPriceBook { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEOfferDocument> TEOfferDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEOfferExpireExtension> TEOfferExpireExtensions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEOfferMileStone> TEOfferMileStones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEOfferPriceBreakUpDetail> TEOfferPriceBreakUpDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEOfferSpecialCondition> TEOfferSpecialConditions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEOfferSpecification> TEOfferSpecifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEOfferTC> TEOfferTCs { get; set; }
    }
}
