//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEOfferRefund
    {
        public int ID { get; set; }
        public int OfferID { get; set; }
        public string SapCustomerid { get; set; }
        public decimal AvailableAmount { get; set; }
        public string PaybleTo { get; set; }
        public System.DateTime RefundDate { get; set; }
        public string PaymentMode { get; set; }
        public decimal Amount { get; set; }
        public string RefundType { get; set; }
        public decimal ForfeitCharges { get; set; }
        public decimal ProposedRefundAmount { get; set; }
        public string Reason { get; set; }
        public string Status { get; set; }
        public string SAPDocumentID { get; set; }
        public Nullable<int> RefundedBy { get; set; }
        public Nullable<System.DateTime> RefundedOn { get; set; }
        public Nullable<int> LastmodifedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<int> SubmittedBy { get; set; }
        public Nullable<System.DateTime> SubmittedOn { get; set; }
    }
}
