//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEOrderApplicant
    {
        public int ApplicantID { get; set; }
        public Nullable<int> ContextID { get; set; }
        public Nullable<int> ContactID { get; set; }
        public string TypeofApplicant { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> DeclarationSigned { get; set; }
        public Nullable<int> OTP { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public Nullable<bool> ISDeleted { get; set; }
    }
}
