//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEPersonalInformationData
    {
        public int UniqueID { get; set; }
        public Nullable<int> TEContact { get; set; }
        public string CurrentProfession { get; set; }
        public string Industry { get; set; }
        public string Company { get; set; }
        public string Designation { get; set; }
        public string IdentityProof { get; set; }
        public string IdentityProofNumber { get; set; }
        public Nullable<System.DateTime> DateOfIssue { get; set; }
        public string AttachmentforIDProofPath { get; set; }
        public string AddressProofDocumentType { get; set; }
        public string AttachmentforAddressProofPath { get; set; }
        public string PANCardNumber { get; set; }
        public string Photo { get; set; }
        public string GeneralPowerOfAttorneyApplicable { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public string LastModifiedByID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string AadharNumber { get; set; }
        public Nullable<System.DateTime> AadharDateOfIssue { get; set; }
        public Nullable<System.DateTime> DateOfValidity { get; set; }
        public string FatherOrHusbandName { get; set; }
    }
}
