//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEPOGLCodeMaster
    {
        public int UniqueID { get; set; }
        public string GLAccountCode { get; set; }
        public string GLAccountDesc { get; set; }
        public string CommitmentItemCode { get; set; }
        public string CommitmentItemDesc { get; set; }
        public string Recon { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string GLAccountShortName { get; set; }
        public string ReconAccntDesc { get; set; }
        public string ReconAccntType { get; set; }
    }
}
