//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEPOReleaseCode
    {
        public string CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string LastModifiedOn { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public int Uniqueid { get; set; }
        public string OldUniqueid { get; set; }
        public string Objectid { get; set; }
        public string FundCenter_Description { get; set; }
        public string FundCenter_Code { get; set; }
        public string Release_Group { get; set; }
        public string ReleaseStrategy { get; set; }
        public string Release_Code1 { get; set; }
        public string ReleaseCode1By { get; set; }
        public string Release_Code2 { get; set; }
        public string ReleaseCode2By { get; set; }
        public string Release_Code3 { get; set; }
        public string ReleaseCode3By { get; set; }
        public string Release_Code4 { get; set; }
        public string ReleaseCode4By { get; set; }
        public string Status { get; set; }
        public string ApprovedBy { get; set; }
        public string ApprovedOn { get; set; }
        public Nullable<int> ApproverId { get; set; }
    }
}
