//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEPOAnnexureSpecification
    {
        public int POAnnexureSpecId { get; set; }
        public string TestObject { get; set; }
        public string TestMethod { get; set; }
        public string Value1 { get; set; }
        public string Value2 { get; set; }
        public string UnitOfMeasurement { get; set; }
        public string Mandatory { get; set; }
        public string AcceptanceCriteria { get; set; }
        public string MTCValue { get; set; }
        public string TestValue { get; set; }
        public string SourceOfTestValue { get; set; }
        public string PassOrFail { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> POAnnexureId { get; set; }
    }
}
