//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEPOService
    {
        public string CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string LastModifiedOn { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public int Uniqueid { get; set; }
        public string OldUniqueid { get; set; }
        public string Objectid { get; set; }
        public string Purchasing_Order_Number { get; set; }
        public string Item_Number { get; set; }
        public string Line_item_number { get; set; }
        public string Activity_Number { get; set; }
        public string Short_Text { get; set; }
        public string Order_Qty { get; set; }
        public string Unit_Measure { get; set; }
        public string Gross_Price { get; set; }
        public string Net_Price { get; set; }
        public string Actual_Qty { get; set; }
        public string line_item { get; set; }
        public string Status { get; set; }
        public string ApprovedBy { get; set; }
        public string ApprovedOn { get; set; }
        public string Version { get; set; }
        public string LongText { get; set; }
        public string teversion { get; set; }
        public string WBS_Element { get; set; }
        public string Fund_Center { get; set; }
        public string Commitment_item { get; set; }
        public string Package_number { get; set; }
        public string Seq_No_Acc_Ass_ESKN { get; set; }
        public string Line_Number_INTROW { get; set; }
        public Nullable<int> POStructureId { get; set; }
        public string SACCode { get; set; }
    }
}
