//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEScheduleMasterNew
    {
        public int ScheduleMasterID { get; set; }
        public string ScheduleName { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> TowerID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> SchemeID { get; set; }
        public Nullable<int> SpecificationID { get; set; }
        public Nullable<int> LastModifiedBy_ID { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string OldUniqueID { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> VersionNo { get; set; }
    }
}
