//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TESmsDetail
    {
        public int SmsID { get; set; }
        public string ContactNumber { get; set; }
        public string Sms_Text { get; set; }
        public string NotificationEvent { get; set; }
        public string SmsStatus { get; set; }
        public Nullable<System.DateTime> SmsSentDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
    }
}
