//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEStampDuty
    {
        public int StampDutyID { get; set; }
        public Nullable<int> OfferId { get; set; }
        public Nullable<decimal> TowardsLand { get; set; }
        public Nullable<decimal> TowardsAmenities { get; set; }
        public Nullable<decimal> TowardsCarPark { get; set; }
        public Nullable<decimal> TotalSaleConsideration { get; set; }
        public Nullable<decimal> StampDutyFee { get; set; }
        public Nullable<decimal> RegistrationFee { get; set; }
        public Nullable<decimal> FloorRiseCharge { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> TotalGuidancePrice { get; set; }
        public Nullable<decimal> FinalSaleConsideration { get; set; }
        public Nullable<decimal> GuideLineRegExpense { get; set; }
        public Nullable<decimal> ProposedRegExpense { get; set; }
        public Nullable<decimal> ActualRegExpense { get; set; }
        public Nullable<decimal> GuideLineStampDuty { get; set; }
        public Nullable<decimal> ActualStampDuty { get; set; }
        public Nullable<decimal> ProposedStampDuty { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<decimal> TotalProposedPrice { get; set; }
        public Nullable<decimal> UnitArea { get; set; }
        public Nullable<decimal> UnitAreaValue { get; set; }
        public Nullable<decimal> FloorRiseValue { get; set; }
        public Nullable<decimal> AmenitiesPercentage { get; set; }
        public Nullable<int> NoOfCarparks { get; set; }
        public Nullable<decimal> CarParkRate { get; set; }
        public Nullable<decimal> ActualRegistrationFee { get; set; }
        public Nullable<decimal> GuideLineRegistrationFee { get; set; }
        public Nullable<decimal> ProposedRegistrationFee { get; set; }
    }
}
