//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TESubProductDetail
    {
        public int ProjectProductID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public string SubProductCode { get; set; }
        public Nullable<decimal> CarPetArea { get; set; }
        public Nullable<decimal> BuiltUpArea { get; set; }
        public Nullable<decimal> StandardPlotArea { get; set; }
        public Nullable<decimal> SaleableArea { get; set; }
        public Nullable<decimal> SuperBuiltUpArea { get; set; }
        public string BaseProductUDI { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> DefaultSpecification { get; set; }
        public string OldUniqueID { get; set; }
        public string Status { get; set; }
        public Nullable<int> UDI { get; set; }
        public Nullable<decimal> BaseAreaMultiplier { get; set; }
        public Nullable<int> VersionNo { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CurrentVelocity { get; set; }
        public Nullable<int> SaleVelocity { get; set; }
        public Nullable<decimal> ReferenceArea { get; set; }
        public string DefaultCustomizationOption { get; set; }
        public Nullable<decimal> RERA_Carpet_Area { get; set; }
        public Nullable<decimal> Outdoor_Area { get; set; }
    
        public virtual TEProduct TEProduct { get; set; }
        public virtual TEProject TEProject { get; set; }
    }
}
