//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TETaxCodeMaster
    {
        public int TaxCodeID { get; set; }
        public string TaxCode { get; set; }
        public Nullable<decimal> TaxRate { get; set; }
        public string SAPTaxCode { get; set; }
        public string ConditionType { get; set; }
        public string TaxType { get; set; }
        public string Description { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public string OldUniqueid { get; set; }
    }
}
