//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TETodaysVisit
    {
        public int TodaysVistID { get; set; }
        public string VisitType { get; set; }
        public Nullable<int> VisitorReference { get; set; }
        public Nullable<System.DateTime> VisitDate { get; set; }
        public Nullable<int> VisitStatus { get; set; }
        public string SiteName { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public string VisitorName { get; set; }
    }
}
