//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TFUserSurvey
    {
        public int UniqueId { get; set; }
        public string UserCode { get; set; }
        public string TFSurveyId { get; set; }
        public string UserType { get; set; }
        public string Email { get; set; }
        public string Name { get; set; }
        public string Browser { get; set; }
        public string Platform { get; set; }
        public Nullable<System.DateTime> DateLand { get; set; }
        public Nullable<System.DateTime> DateSubmit { get; set; }
        public string UserAgent { get; set; }
        public string Referer { get; set; }
        public string NetworkId { get; set; }
        public Nullable<byte> IsSubmitted { get; set; }
    }
}
