//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class webpages_Roles
    {
        public int RoleId { get; set; }
        public string RoleName { get; set; }
        public string BizAppID { get; set; }
    
        public virtual webpages_Roles webpages_Roles1 { get; set; }
        public virtual webpages_Roles webpages_Roles2 { get; set; }
    }
}
