//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEComplaintsManagementDAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class TEHRIS_DevEntities : DbContext
    {
        public TEHRIS_DevEntities()
            : base("name=TEHRIS_DevEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ApplicationErrorLog> ApplicationErrorLogs { get; set; }
        public DbSet<DataBaseLog> DataBaseLogs { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<TEActivityTimelineInfo> TEActivityTimelineInfoes { get; set; }
        public DbSet<TEAnswer> TEAnswers { get; set; }
        public DbSet<TEBandsAndGrade> TEBandsAndGrades { get; set; }
        public DbSet<TECampaign> TECampaigns { get; set; }
        public DbSet<TECategory> TECategories { get; set; }
        public DbSet<TEChangeLog> TEChangeLogs { get; set; }
        public DbSet<TEComment> TEComments { get; set; }
        public DbSet<TECompany> TECompanies { get; set; }
        public DbSet<TEContact> TEContacts { get; set; }
        public DbSet<TEContactAddress> TEContactAddresses { get; set; }
        public DbSet<TEContactAlumni> TEContactAlumnis { get; set; }
        public DbSet<TEContactEmail> TEContactEmails { get; set; }
        public DbSet<TEContactGPA> TEContactGPAs { get; set; }
        public DbSet<TEContactIdentification> TEContactIdentifications { get; set; }
        public DbSet<TEContactInterest> TEContactInterests { get; set; }
        public DbSet<TEContactMobile> TEContactMobiles { get; set; }
        public DbSet<TEContactOrganisation> TEContactOrganisations { get; set; }
        public DbSet<TEContactProfession> TEContactProfessions { get; set; }
        public DbSet<TEContactRelation> TEContactRelations { get; set; }
        public DbSet<TEContactSocial> TEContactSocials { get; set; }
        public DbSet<TEDepartment> TEDepartments { get; set; }
        public DbSet<TEDocument> TEDocuments { get; set; }
        public DbSet<TEEmailStatu> TEEmailStatus { get; set; }
        public DbSet<TEEmailTemplate> TEEmailTemplates { get; set; }
        public DbSet<TEEmailTemplateAttachment> TEEmailTemplateAttachments { get; set; }
        public DbSet<TEEMPAddress> TEEMPAddresses { get; set; }
        public DbSet<TEEmpAssignmentDetail> TEEmpAssignmentDetails { get; set; }
        public DbSet<TEEmpAttendence> TEEmpAttendences { get; set; }
        public DbSet<TEEmpBankDetail> TEEmpBankDetails { get; set; }
        public DbSet<TEEmpBasicInfo> TEEmpBasicInfoes { get; set; }
        public DbSet<TEEmpEducationDetail> TEEmpEducationDetails { get; set; }
        public DbSet<TEEmpEmergencyContact> TEEmpEmergencyContacts { get; set; }
        public DbSet<TEEmpExperienceDetail> TEEmpExperienceDetails { get; set; }
        public DbSet<TEEmpFamilyDetail> TEEmpFamilyDetails { get; set; }
        public DbSet<TEEmpInsuranceDetail> TEEmpInsuranceDetails { get; set; }
        public DbSet<TEEmpLanguage> TEEmpLanguages { get; set; }
        public DbSet<TEEmpLeaveApplication> TEEmpLeaveApplications { get; set; }
        public DbSet<TEEmpLeavesSummary> TEEmpLeavesSummaries { get; set; }
        public DbSet<TEEmpOtherDetail> TEEmpOtherDetails { get; set; }
        public DbSet<TEEmpReference> TEEmpReferences { get; set; }
        public DbSet<TEEmpWorkSchedule> TEEmpWorkSchedules { get; set; }
        public DbSet<TEESCALATION> TEESCALATIONs { get; set; }
        public DbSet<TEESCALATIONMATRIX> TEESCALATIONMATRIces { get; set; }
        public DbSet<TEHoliday_TEWorkLocation_Mappings> TEHoliday_TEWorkLocation_Mappings { get; set; }
        public DbSet<TEHoliday> TEHolidays { get; set; }
        public DbSet<TEIssue> TEIssues { get; set; }
        public DbSet<TELead> TELeads { get; set; }
        public DbSet<TELeadInterestedProjectid> TELeadInterestedProjectids { get; set; }
        public DbSet<TELeadSalesCoassignman> TELeadSalesCoassignmen { get; set; }
        public DbSet<TELeadStatusTrack> TELeadStatusTracks { get; set; }
        public DbSet<TELeaveType> TELeaveTypes { get; set; }
        public DbSet<TELineOfBusiness> TELineOfBusinesses { get; set; }
        public DbSet<TENote> TENotes { get; set; }
        public DbSet<TEOffer> TEOffers { get; set; }
        public DbSet<TEOtherDetail> TEOtherDetails { get; set; }
        public DbSet<TEPickListItem> TEPickListItems { get; set; }
        public DbSet<TEPickList> TEPickLists { get; set; }
        public DbSet<TEProject> TEProjects { get; set; }
        public DbSet<TEProjects_TOWER> TEProjects_TOWER { get; set; }
        public DbSet<TEProjects_UNIT> TEProjects_UNIT { get; set; }
        public DbSet<TEQuestion> TEQuestions { get; set; }
        public DbSet<TEQueue> TEQueues { get; set; }
        public DbSet<TEQueueDepartment> TEQueueDepartments { get; set; }
        public DbSet<TERequestAssignment> TERequestAssignments { get; set; }
        public DbSet<TERule> TERules { get; set; }
        public DbSet<TESubFunction> TESubFunctions { get; set; }
        public DbSet<TESurvey> TESurveys { get; set; }
        public DbSet<TETask> TETasks { get; set; }
        public DbSet<TEUnit_Onboarding> TEUnit_Onboarding { get; set; }
        public DbSet<TEVisitorPass> TEVisitorPasses { get; set; }
        public DbSet<TEWorkingDesignation> TEWorkingDesignations { get; set; }
        public DbSet<TEWorkLocation> TEWorkLocations { get; set; }
        public DbSet<UserProfile> UserProfiles { get; set; }
        public DbSet<webpages_Membership> webpages_Membership { get; set; }
        public DbSet<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }
        public DbSet<webpages_Roles> webpages_Roles { get; set; }
    
        public virtual ObjectResult<Proc_CategoryDepartment_Result> Proc_CategoryDepartment(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_CategoryDepartment_Result>("Proc_CategoryDepartment", iDParameter);
        }
    }
}
