//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEComplaintsManagementDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEEmpInsuranceDetail
    {
        public int Uniqueid { get; set; }
        public string Olduniqueid { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
        public string ApprovedBy { get; set; }
        public string ObjectId { get; set; }
        public int TEEmpBasicInfo { get; set; }
        public string IDNumber { get; set; }
        public string InsuredPersonType { get; set; }
        public string NameofInsured { get; set; }
        public string PolicyNumber { get; set; }
        public string PolicyType { get; set; }
        public System.DateTime PlanPeriodFrom { get; set; }
        public Nullable<System.DateTime> PlanPeriodTo { get; set; }
        public string Insurer { get; set; }
        public string InsuranceCompanyName { get; set; }
        public string Status { get; set; }
    
        public virtual TEEmpBasicInfo TEEmpBasicInfo1 { get; set; }
    }
}
