//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEComplaintsManagementDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEIssue
    {
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public string LastModifiedBy { get; set; }
        public bool IsDeleted { get; set; }
        public int Uniqueid { get; set; }
        public string OldUniqueid { get; set; }
        public string Objectid { get; set; }
        public Nullable<int> ISSUEID { get; set; }
        public string UNITONBOARDINGID { get; set; }
        public string Subject { get; set; }
        public string Descritpion { get; set; }
        public string Summary { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> ParentCatID { get; set; }
        public Nullable<int> QueueID { get; set; }
        public Nullable<System.DateTime> Closed_Date { get; set; }
        public string Priority { get; set; }
        public string Status { get; set; }
        public string Stage { get; set; }
        public string AssignedTo { get; set; }
        public string ClosedBy { get; set; }
        public string RaisedBy { get; set; }
        public string Attachments { get; set; }
        public Nullable<System.DateTime> Estimated_Close_date { get; set; }
        public Nullable<System.DateTime> Actual_close_date { get; set; }
        public Nullable<System.DateTime> Assigned { get; set; }
        public Nullable<System.DateTime> Start { get; set; }
        public Nullable<System.DateTime> Pasue { get; set; }
        public Nullable<System.DateTime> Deferred_Date { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public string UnitID { get; set; }
        public string AREATYPE { get; set; }
        public Nullable<System.DateTime> Scheduled_Date { get; set; }
        public string RateUS { get; set; }
        public Nullable<int> COSTINVOLED { get; set; }
        public Nullable<int> EstimateCOST { get; set; }
        public Nullable<int> ActualCost { get; set; }
        public Nullable<int> LaborCost { get; set; }
        public Nullable<int> MaterialCost { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
    }
}
