//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEComplaintsManagementDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEOffer
    {
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public string LastModifiedBy { get; set; }
        public bool IsDeleted { get; set; }
        public int Uniqueid { get; set; }
        public string OldUniqueid { get; set; }
        public string Objectid { get; set; }
        public string OfferName { get; set; }
        public Nullable<int> TEprojectid { get; set; }
        public string ProjectName { get; set; }
        public Nullable<int> TEUnitid { get; set; }
        public string UnitNumber { get; set; }
        public Nullable<int> TEProductId { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> TESubProductId { get; set; }
        public string SubProductName { get; set; }
        public string SpecsType { get; set; }
        public Nullable<long> ListPrice { get; set; }
        public Nullable<long> ListRate { get; set; }
        public Nullable<long> OfferPrice { get; set; }
        public Nullable<long> OfferRate { get; set; }
        public Nullable<long> ConsiderationPrice { get; set; }
        public Nullable<long> ConsiderationRate { get; set; }
        public Nullable<long> ResidentialUnitPrice { get; set; }
        public Nullable<long> ResidentialUnitRate { get; set; }
        public Nullable<long> BasePrice { get; set; }
        public Nullable<long> BaseRate { get; set; }
        public string BasePriceType { get; set; }
        public Nullable<long> SpecificFloorRate { get; set; }
        public Nullable<long> SpecificFloorPrice { get; set; }
        public string SpecificFloorType { get; set; }
        public Nullable<long> PremiumADVRate { get; set; }
        public Nullable<long> PremiumADVPrice { get; set; }
        public string PremiumADVType { get; set; }
        public Nullable<long> AmenitiesRate { get; set; }
        public Nullable<long> AmenitiesPrice { get; set; }
        public string AmenitiesTYPE { get; set; }
        public Nullable<long> CarParkRate { get; set; }
        public Nullable<long> CarParkPrice { get; set; }
        public Nullable<long> EBuildRate { get; set; }
        public Nullable<long> EBuildPrice { get; set; }
        public string EBuildType { get; set; }
        public Nullable<long> PersonalisedDesignRate { get; set; }
        public Nullable<long> PersonalisedDesignPrice { get; set; }
        public string PersonalisedDesignType { get; set; }
        public Nullable<long> UtilitiesRate { get; set; }
        public Nullable<long> UtilitiesPrice { get; set; }
        public string UtilitiesType { get; set; }
        public Nullable<long> AdditionalLandPrice { get; set; }
        public Nullable<int> AdditionalLandSqft { get; set; }
        public Nullable<long> MaintenanceFundPrice { get; set; }
        public Nullable<long> MaintenanceFundRate { get; set; }
        public string MAaintenanceFundArea { get; set; }
        public string SalebleArea { get; set; }
        public string BuiltupArea { get; set; }
        public string PlotArea { get; set; }
        public string CarpetArea { get; set; }
        public string ReferenceSaleableArea { get; set; }
        public string SaleableAreaBasis { get; set; }
        public string HomeImprovement { get; set; }
        public Nullable<long> UpgradeCharges { get; set; }
        public Nullable<long> EffectivedDiscount { get; set; }
        public Nullable<long> PricedDiscount { get; set; }
        public Nullable<long> TowardsBasicCost { get; set; }
        public string TowardsPaymentTerms { get; set; }
        public Nullable<long> MilestoneAdjustmentDiscount { get; set; }
        public string CustimizationCredit { get; set; }
        public Nullable<long> SpecialConditionsDiscount { get; set; }
        public Nullable<long> BrokerageFeeDiscount { get; set; }
        public Nullable<long> LandCost { get; set; }
        public Nullable<long> CostructionCost { get; set; }
        public string MaintaianceFund { get; set; }
        public Nullable<long> ESTServiceTax { get; set; }
        public Nullable<long> ESTVatTax { get; set; }
        public Nullable<long> NPVDiscountValue { get; set; }
        public Nullable<int> DiscountCalculatorPercentage { get; set; }
        public string RevisionNo { get; set; }
        public string RevisionStatus { get; set; }
        public string OfferStatus { get; set; }
        public string OrderStatus { get; set; }
        public string SuborderStatus { get; set; }
        public string MergedUnit { get; set; }
        public string Status { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
    }
}
