//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace PO.VendorSAPServiceInterface {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="VendorMaster_OutBinding", Namespace="http://total-environment/PI/VendorMaster")]
    public partial class VendorMaster_OutService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback VendorMaster_OutOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public VendorMaster_OutService() {
            this.Url = global::PO.Properties.Settings.Default.PO_VendorSAPServiceInterface_VendorMaster_OutService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event VendorMaster_OutCompletedEventHandler VendorMaster_OutCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlArrayAttribute("VendorMasterRes", Namespace="http://total-environment/PI/VendorMaster")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public VendorMasterResItem[] VendorMaster_Out([System.Xml.Serialization.XmlArrayAttribute(Namespace="http://total-environment/PI/VendorMaster")] [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)] VendorMasterReqItem[] VendorMasterReq) {
            object[] results = this.Invoke("VendorMaster_Out", new object[] {
                        VendorMasterReq});
            return ((VendorMasterResItem[])(results[0]));
        }
        
        /// <remarks/>
        public void VendorMaster_OutAsync(VendorMasterReqItem[] VendorMasterReq) {
            this.VendorMaster_OutAsync(VendorMasterReq, null);
        }
        
        /// <remarks/>
        public void VendorMaster_OutAsync(VendorMasterReqItem[] VendorMasterReq, object userState) {
            if ((this.VendorMaster_OutOperationCompleted == null)) {
                this.VendorMaster_OutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVendorMaster_OutOperationCompleted);
            }
            this.InvokeAsync("VendorMaster_Out", new object[] {
                        VendorMasterReq}, this.VendorMaster_OutOperationCompleted, userState);
        }
        
        private void OnVendorMaster_OutOperationCompleted(object arg) {
            if ((this.VendorMaster_OutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VendorMaster_OutCompleted(this, new VendorMaster_OutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://total-environment/PI/VendorMaster")]
    public partial class VendorMasterReqItem {
        
        private string lIFNRField;
        
        private string bUKRSField;
        
        private string eKORGField;
        
        private string kTOKKField;
        
        private string nAME1Field;
        
        private string nAME2Field;
        
        private string nAME3Field;
        
        private string nAME4Field;
        
        private string sTREETField;
        
        private string sTREET2Field;
        
        private string sTREET3Field;
        
        private string pOST_CODE1Field;
        
        private string cITY1Field;
        
        private string cOUNTRYField;
        
        private string rEGIONField;
        
        private string tEL_NUMBERField;
        
        private string sMTP_ADDRField;
        
        private string aKONTField;
        
        private string zTERMField;
        
        private string zWELSField;
        
        private string rEPRFField;
        
        private string qLANDField;
        
        private string wAERSField;
        
        private string kALSKField;
        
        private string bUSABField;
        
        private string sORT1Field;
        
        private string wEBREField;
        
        private string lEBREField;
        
        private string vERKFField;
        
        private string lNRZAField;
        
        private string xZEMPField;
        
        private string j_1ICSTNOField;
        
        private string j_1ILSTNOField;
        
        private string j_1ISERNField;
        
        private string j_1IEXRNField;
        
        private string j_1IPANNOField;
        
        private string fUGUE_IDField;
        
        private string sTCD3Field;
        
        private string vEN_CLASSField;
        
        private string pARVWField;
        
        private string pARNRField;
        
        private VendorMasterReqItemItem[] itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LIFNR {
            get {
                return this.lIFNRField;
            }
            set {
                this.lIFNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BUKRS {
            get {
                return this.bUKRSField;
            }
            set {
                this.bUKRSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EKORG {
            get {
                return this.eKORGField;
            }
            set {
                this.eKORGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KTOKK {
            get {
                return this.kTOKKField;
            }
            set {
                this.kTOKKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NAME1 {
            get {
                return this.nAME1Field;
            }
            set {
                this.nAME1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NAME2 {
            get {
                return this.nAME2Field;
            }
            set {
                this.nAME2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NAME3 {
            get {
                return this.nAME3Field;
            }
            set {
                this.nAME3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NAME4 {
            get {
                return this.nAME4Field;
            }
            set {
                this.nAME4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STREET {
            get {
                return this.sTREETField;
            }
            set {
                this.sTREETField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STREET2 {
            get {
                return this.sTREET2Field;
            }
            set {
                this.sTREET2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STREET3 {
            get {
                return this.sTREET3Field;
            }
            set {
                this.sTREET3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string POST_CODE1 {
            get {
                return this.pOST_CODE1Field;
            }
            set {
                this.pOST_CODE1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CITY1 {
            get {
                return this.cITY1Field;
            }
            set {
                this.cITY1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string COUNTRY {
            get {
                return this.cOUNTRYField;
            }
            set {
                this.cOUNTRYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string REGION {
            get {
                return this.rEGIONField;
            }
            set {
                this.rEGIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TEL_NUMBER {
            get {
                return this.tEL_NUMBERField;
            }
            set {
                this.tEL_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SMTP_ADDR {
            get {
                return this.sMTP_ADDRField;
            }
            set {
                this.sMTP_ADDRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AKONT {
            get {
                return this.aKONTField;
            }
            set {
                this.aKONTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZTERM {
            get {
                return this.zTERMField;
            }
            set {
                this.zTERMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZWELS {
            get {
                return this.zWELSField;
            }
            set {
                this.zWELSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string REPRF {
            get {
                return this.rEPRFField;
            }
            set {
                this.rEPRFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QLAND {
            get {
                return this.qLANDField;
            }
            set {
                this.qLANDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WAERS {
            get {
                return this.wAERSField;
            }
            set {
                this.wAERSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KALSK {
            get {
                return this.kALSKField;
            }
            set {
                this.kALSKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BUSAB {
            get {
                return this.bUSABField;
            }
            set {
                this.bUSABField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SORT1 {
            get {
                return this.sORT1Field;
            }
            set {
                this.sORT1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WEBRE {
            get {
                return this.wEBREField;
            }
            set {
                this.wEBREField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LEBRE {
            get {
                return this.lEBREField;
            }
            set {
                this.lEBREField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VERKF {
            get {
                return this.vERKFField;
            }
            set {
                this.vERKFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LNRZA {
            get {
                return this.lNRZAField;
            }
            set {
                this.lNRZAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string XZEMP {
            get {
                return this.xZEMPField;
            }
            set {
                this.xZEMPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string J_1ICSTNO {
            get {
                return this.j_1ICSTNOField;
            }
            set {
                this.j_1ICSTNOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string J_1ILSTNO {
            get {
                return this.j_1ILSTNOField;
            }
            set {
                this.j_1ILSTNOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string J_1ISERN {
            get {
                return this.j_1ISERNField;
            }
            set {
                this.j_1ISERNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string J_1IEXRN {
            get {
                return this.j_1IEXRNField;
            }
            set {
                this.j_1IEXRNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string J_1IPANNO {
            get {
                return this.j_1IPANNOField;
            }
            set {
                this.j_1IPANNOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FUGUE_ID {
            get {
                return this.fUGUE_IDField;
            }
            set {
                this.fUGUE_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STCD3 {
            get {
                return this.sTCD3Field;
            }
            set {
                this.sTCD3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VEN_CLASS {
            get {
                return this.vEN_CLASSField;
            }
            set {
                this.vEN_CLASSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PARVW {
            get {
                return this.pARVWField;
            }
            set {
                this.pARVWField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PARNR {
            get {
                return this.pARNRField;
            }
            set {
                this.pARNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public VendorMasterReqItemItem[] item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://total-environment/PI/VendorMaster")]
    public partial class VendorMasterReqItemItem {
        
        private string lIFNRField;
        
        private string wITHTField;
        
        private string wT_SUBJCTField;
        
        private string wT_WITHCDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LIFNR {
            get {
                return this.lIFNRField;
            }
            set {
                this.lIFNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WITHT {
            get {
                return this.wITHTField;
            }
            set {
                this.wITHTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WT_SUBJCT {
            get {
                return this.wT_SUBJCTField;
            }
            set {
                this.wT_SUBJCTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WT_WITHCD {
            get {
                return this.wT_WITHCDField;
            }
            set {
                this.wT_WITHCDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://total-environment/PI/VendorMaster")]
    public partial class VendorMasterResItem {
        
        private string lIFNRField;
        
        private string bUKRSField;
        
        private string rETCODEField;
        
        private string mESSAGEField;
        
        private string fUGUE_IDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LIFNR {
            get {
                return this.lIFNRField;
            }
            set {
                this.lIFNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BUKRS {
            get {
                return this.bUKRSField;
            }
            set {
                this.bUKRSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RETCODE {
            get {
                return this.rETCODEField;
            }
            set {
                this.rETCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FUGUE_ID {
            get {
                return this.fUGUE_IDField;
            }
            set {
                this.fUGUE_IDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void VendorMaster_OutCompletedEventHandler(object sender, VendorMaster_OutCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VendorMaster_OutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VendorMaster_OutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public VendorMasterResItem[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((VendorMasterResItem[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591